<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.21">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="author" content="Ismael Aguayo y Catalina Soza">
<title>Operacionalización y validación de escala de uso de dispositivos para ocio y socialización en adultos mayores</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="análisis_files/libs/clipboard/clipboard.min.js"></script>
<script src="análisis_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="análisis_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="análisis_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="análisis_files/libs/quarto-html/popper.min.js"></script>
<script src="análisis_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="análisis_files/libs/quarto-html/anchor.min.js"></script>
<link href="análisis_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="análisis_files/libs/quarto-html/quarto-syntax-highlighting-ea1d7ac60288e0f1efdbc993fd8432ae.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="análisis_files/libs/quarto-html/quarto-syntax-highlighting-dark-7e9717d9caa9b4d114d189eaeb260ada.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="análisis_files/libs/quarto-html/quarto-syntax-highlighting-ea1d7ac60288e0f1efdbc993fd8432ae.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="análisis_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="análisis_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="análisis_files/libs/bootstrap/bootstrap-c2982a1808f62c7d890af9a486812753.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="análisis_files/libs/bootstrap/bootstrap-dark-a4568acb073e11179db58c239e51caf7.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="análisis_files/libs/bootstrap/bootstrap-c2982a1808f62c7d890af9a486812753.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light"><style>html{ scroll-behavior: smooth; }</style>
<script type="application/json" class="js-hypothesis-config">
{
  "theme": "classic",
  "openSidebar": false
}
</script><script async="" src="https://hypothes.is/embed.js"></script><script>
  window.document.addEventListener("DOMContentLoaded", function (_event) {
    document.body.classList.add('hypothesis-enabled');
  });
</script><link href="an%C3%A1lisis_files/libs/table1-1.0/table1_defaults.css" rel="stylesheet">
<link href="an%C3%A1lisis_files/libs/tabwid-1.1.3/tabwid.css" rel="stylesheet">
<script src="an%C3%A1lisis_files/libs/tabwid-1.1.3/tabwid.js"></script><script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>
</head>
<body class="quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<header id="title-block-header" class="quarto-title-block default toc-left page-columns page-full"><div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Operacionalización y validación de escala de uso de dispositivos para ocio y socialización en adultos mayores</h1>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Autor/a</div>
      <div class="quarto-title-meta-contents">
               <p>Ismael Aguayo y Catalina Soza </p>
            </div>
    </div>
      
    
      
    </div>
    
  
  </header><div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Índice</h2>
   
  <ul>
<li><a href="#introducci%C3%B3n" id="toc-introducción" class="nav-link active" data-scroll-target="#introducci%C3%B3n"><span class="header-section-number">1</span> Introducción</a></li>
  <li><a href="#ocio-y-socializaci%C3%B3n-digital-vs.-usos-instrumentales-de-las-tic" id="toc-ocio-y-socialización-digital-vs.-usos-instrumentales-de-las-tic" class="nav-link" data-scroll-target="#ocio-y-socializaci%C3%B3n-digital-vs.-usos-instrumentales-de-las-tic"><span class="header-section-number">2</span> Ocio y socialización digital vs.&nbsp;usos instrumentales de las TIC</a></li>
  <li>
<a href="#mediciones-de-ocio-y-socializaci%C3%B3n-digital-en-la-vejez" id="toc-mediciones-de-ocio-y-socialización-digital-en-la-vejez" class="nav-link" data-scroll-target="#mediciones-de-ocio-y-socializaci%C3%B3n-digital-en-la-vejez"><span class="header-section-number">3</span> Mediciones de ocio y socialización digital en la vejez</a>
  <ul class="collapse">
<li><a href="#escala-de-uso-de-dispositivos-digitales-para-ocio-y-socializaci%C3%B3n-en-adultos-mayores" id="toc-escala-de-uso-de-dispositivos-digitales-para-ocio-y-socialización-en-adultos-mayores" class="nav-link" data-scroll-target="#escala-de-uso-de-dispositivos-digitales-para-ocio-y-socializaci%C3%B3n-en-adultos-mayores"><span class="header-section-number">3.1</span> Escala de uso de dispositivos digitales para ocio y socialización en adultos mayores</a></li>
  </ul>
</li>
  <li><a href="#evaluaci%C3%B3n-de-datos-disponibles-y-propuesta-de-instrumento" id="toc-evaluación-de-datos-disponibles-y-propuesta-de-instrumento" class="nav-link" data-scroll-target="#evaluaci%C3%B3n-de-datos-disponibles-y-propuesta-de-instrumento"><span class="header-section-number">4</span> <strong>Evaluación de datos disponibles y propuesta de instrumento</strong></a></li>
  <li>
<a href="#datos" id="toc-datos" class="nav-link" data-scroll-target="#datos"><span class="header-section-number">5</span> Datos</a>
  <ul class="collapse">
<li><a href="#escala-de-uso-de-dispositivos-digitales-para-ocio-y-socializaci%C3%B3n-en-adultos-mayores-adaptada" id="toc-escala-de-uso-de-dispositivos-digitales-para-ocio-y-socialización-en-adultos-mayores-adaptada" class="nav-link" data-scroll-target="#escala-de-uso-de-dispositivos-digitales-para-ocio-y-socializaci%C3%B3n-en-adultos-mayores-adaptada"><span class="header-section-number">5.1</span> Escala de uso de dispositivos digitales para ocio y socialización en adultos mayores adaptada</a></li>
  <li><a href="#variables-dependientes" id="toc-variables-dependientes" class="nav-link" data-scroll-target="#variables-dependientes"><span class="header-section-number">5.2</span> Variables dependientes</a></li>
  <li><a href="#hip%C3%B3tesis" id="toc-hipótesis" class="nav-link" data-scroll-target="#hip%C3%B3tesis"><span class="header-section-number">5.3</span> Hipótesis</a></li>
  </ul>
</li>
  <li>
<a href="#resultados" id="toc-resultados" class="nav-link" data-scroll-target="#resultados"><span class="header-section-number">6</span> Resultados</a>
  <ul class="collapse">
<li><a href="#configuraci%C3%B3n-de-la-sesi%C3%B3n" id="toc-configuración-de-la-sesión" class="nav-link" data-scroll-target="#configuraci%C3%B3n-de-la-sesi%C3%B3n"><span class="header-section-number">6.1</span> Configuración de la sesión</a></li>
  <li><a href="#preprocesamiento-de-los-datos" id="toc-preprocesamiento-de-los-datos" class="nav-link" data-scroll-target="#preprocesamiento-de-los-datos"><span class="header-section-number">6.2</span> Preprocesamiento de los datos</a></li>
  <li><a href="#resultados-descriptivos" id="toc-resultados-descriptivos" class="nav-link" data-scroll-target="#resultados-descriptivos"><span class="header-section-number">6.3</span> Resultados descriptivos</a></li>
  <li><a href="#validaci%C3%B3n-de-la-escala" id="toc-validación-de-la-escala" class="nav-link" data-scroll-target="#validaci%C3%B3n-de-la-escala"><span class="header-section-number">6.4</span> Validación de la escala</a></li>
  <li><a href="#resultados-bivariados" id="toc-resultados-bivariados" class="nav-link" data-scroll-target="#resultados-bivariados"><span class="header-section-number">6.5</span> Resultados bivariados</a></li>
  </ul>
</li>
  <li><a href="#referencias" id="toc-referencias" class="nav-link" data-scroll-target="#referencias"><span class="header-section-number">7</span> <strong>Referencias</strong></a></li>
  </ul></nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
</div>
<main class="content quarto-banner-title-block" id="quarto-document-content"><section id="introducción" class="level2" data-number="1"><h2 data-number="1" class="anchored" data-anchor-id="introducción">
<span class="header-section-number">1</span> Introducción</h2>
<p>El envejecimiento de la población es un cambio demográfico que está sucediendo en todo el mundo. Se caracteriza porque hay cada vez más personas mayores, y la esperanza de vida es más alta (Organización Mundial de la Salud, 2025). Chile, por su parte, también refleja esta tendencia global, presentando un marcado y acelerado proceso de envejecimiento. Los datos del Censo 2024 (Instituto Nacional de Estadística, 2025) indican que el porcentaje de personas de 65 años o más alcanzó el 14%, en contraste con el 6,6% en 1992, elevando el Índice de Envejecimiento a 79 personas mayores por cada 100 menores de 15 años.</p>
<p>Por otro lado, las Tecnologías de la Información y Comunicación (TIC) son cruciales en el mundo contemporáneo, impactando áreas tan diversas como la educación, el trabajo, la comunicación y la vida cotidiana (Castells, 1997; Van Dijk, 2020b). No obstante, la transformación digital no se ha distribuido de manera equitativa para la población (Van Dijk, 2020a). Esta desigualdad puede entenderse a través del concepto de <em>digital divide</em>, entendida como un fenómeno multifacético que refleja las desigualdades en el acceso, uso y aprovechamiento de las TIC entre distintos grupos sociales. Esta brecha es más aguda en adultos mayores (Mubarak y Suomi, 2022, Barrenda et al.&nbsp;2024), los cuales han tenido profundas desventajas en habilidades, tipos de uso y resultados asociados al uso de TIC, desarrollándose el concepto de <em>grey digital divide</em> para su caso particular.</p>
<p>Esto es especialmente relevante, ya que la literatura revela los posibles beneficios que tiene el uso de TICs en la población envejecida. Entre ellos, se encuentran la reducción de sintomatología depresiva e ideación suicida y el aumento de la satisfacción con la vida (Jun y Kim, 2017; Lifshitz et al., 2018; Wang et al., 2019). Sumado a esto, el uso de las TIC favorece la conectividad social (Forsman y Nordmyr, 2017; Szabo et al., 2019), el acceso a los recursos comunitarios (Forsman y Nordmyr, 2017) y la participación e inclusión social (Forsman y Nordmyr, 2017; Ihm y Hsieh, 2015). Además, las TIC en la actualidad son clave para la socialización, ya que permiten la conexión ininterrumpida con otras personas, trascendiendo las barreras geográficas y culturales y ofreciendo nuevas oportunidades para la conexión social (Kaye, 2021; Rosell et al., 2024). Específicamente, para usos sociales y motivados por el ocio, la utilización de herramientas digitales en la vejez tiene un impacto especialmente significativo en la salud mental de los adultos mayores, por sobre otros tipos de uso informacionales e instrumentales (Szabo et al., 2019; Sims et al., 2017).</p>
<p>En el contexto nacional, el uso de internet y dispositivos digitales está aumentando exponencialmente en personas mayores, por lo que las brechas de acceso están disminuyendo. Según la Sexta Encuesta Nacional de Calidad de Vida en la Vejez 2022 (ENCVV), un 89% de los encuestados reportaron tener celular para uso propio, aumentando casi en 40 % desde el 2019. Sumado a esto, el estudio de la undécima Encuesta sobre acceso, usos y usuarios de Internet en Chile (Subsecretaría de Telecomunicaciones y CADEM, 2024) reportó que un 82,9 % de los adultos mayores tiene acceso propio y pagado a Internet en el hogar.</p>
<p>Sin embargo, la brecha digital ya no responde a la simple tenencia o no de una conexión wifi, o de un celular inteligente. En la actualidad, la forma de uso que se le da a los dispositivos digitales impacta en los resultados que se puede tener en la vida (Van Dijk, 2020a), y, como se referenció anteriormente, en componentes cruciales de la salud mental de los adultos mayores.</p>
</section><section id="ocio-y-socialización-digital-vs.-usos-instrumentales-de-las-tic" class="level2" data-number="2"><h2 data-number="2" class="anchored" data-anchor-id="ocio-y-socialización-digital-vs.-usos-instrumentales-de-las-tic">
<span class="header-section-number">2</span> Ocio y socialización digital vs.&nbsp;usos instrumentales de las TIC</h2>
<p>En este estudio, se entenderán ocio y socialización digital cómo el conjunto de prácticas y actividades, mediadas por tecnologías y dispositivos digitales (como smartphones, computadores o tablets), que los adultos mayores realizan con el propósito principal de obtener gratificación personal, entretenimiento, descanso y para mantener o expandir sus redes de interacción social.</p>
<p>Se decide realizar una medición específica del ocio y la socialización digital, excluyendo deliberadamente otros indicadores de uso, por dos razones teóricas y empíricas concatenadas.</p>
<p>Primero, la literatura especializada distingue los tipos de uso de Internet según su motivación subyacente. Por un lado, existen usos instrumentales o utilitarios, que están orientados a la consecución de tareas y metas externas (ej. realizar trámites bancarios, compras, buscar información de salud). Por otro lado, existen usos socioemocionales y de ocio, cuyo propósito es intrínseco y está vinculado directamente a la gratificación personal, el entretenimiento y la regulación de las relaciones sociales (Stafford et al., 2004).</p>
<p>Segundo, la evidencia empírica sugiere que estos distintos tipos de uso impactan de manera diferenciada en el bienestar de las personas mayores. Mientras los usos instrumentales pueden mejorar la autonomía, son los usos sociales y de ocio los que demuestran una relación más directa y robusta con los indicadores de bienestar psicológico. Por ejemplo, Sims et al.&nbsp;(2017) encuentra que, en adultos de 80 años y más, el uso de Internet para propósitos sociales se asociaba con una mayor satisfacción vital, mientras que el uso para fines informacionales no presentaba un efecto significativo sobre esta. De forma similar, el estudio longitudinal de Szabo et al.&nbsp;(2019) concluyó que el uso social de Internet impactaba positivamente en el bienestar al reducir la soledad, relación que no se encontró para los usos instrumentales o informacionales.</p>
<p>Por lo tanto, al centrar este estudio en el ocio y la socialización, se busca capturar las prácticas digitales que están más directa e intrínsecamente ligadas a la regulación socioemocional y al bienestar psicológico de la población mayor, lo cual es central para nuestras hipótesis de trabajo. Para motivos de este estudio, se entenderá por adultos mayores a personas de más de 60 años, según lo establecido en la legislación actual chilena (ley N°19.828).</p>
</section><section id="mediciones-de-ocio-y-socialización-digital-en-la-vejez" class="level2" data-number="3"><h2 data-number="3" class="anchored" data-anchor-id="mediciones-de-ocio-y-socialización-digital-en-la-vejez">
<span class="header-section-number">3</span> Mediciones de ocio y socialización digital en la vejez</h2>
<p>El ocio y socialización digital en la vejez se ha medido de mútiples formas y en distintos contextos y estudios, sin embargo, típicamente de forma independiente.</p>
<p>Para medir el ocio digital, Rosell y Vergés (2021), crearon y aplicaron una encuesta, en la cual, cuatro ítems son dirigidos hacia actividades de ocio digital. Estos ítems consisten en preguntar por las actividades de ocio en línea, tales como videojuegos, escuchar música, ver televisión y leer libros o revistas, a través de la utilización de distintos dispositivos electrónicos (p.&nbsp;ej., notebook, iPad, tablet, smartphone y consola de videojuegos). El formato de respuesta del ítem refiere a la frecuencia con la que se realizaron estas actividades, variando desde la opción “nunca” hasta el número de días en un mes dividido en rangos de 5 días (p.&nbsp;ej., de 1 a 5 días, de 6 a 10 días, etc.).</p>
<p>En cuanto a la socialización, Szabo et al.&nbsp;(2019) utiliza datos del <em>New Zealand Health, Work, and Retirement Study</em> y construye un índice de uso de internet para socialización en adultos mayores (el cual es validado utilizando Análisis Factorial Confirmatorio, que señala un ajuste pobre del modelo). El estudio mide este concepto a través de cuatro variables: relación con amigos, relación con familiares, creación de nuevas relaciones con amigos y familiares y compartir fotografías y datos. Todas las variables son medidas a través de escalas Likert de frecuencia, con las categorías (1) Nunca; (2) una vez cada algunos meses; (3) una vez al mes; (4) varias veces al mes; (5) varias veces a la semana y (6) diariamente.</p>
<p>En el contexto nacional, la ENCVV (Centro de Estudios de Vejez y Envejecimiento UC &amp; Caja Los Andes, 2022) aplica un módulo dedicado específicamente a tecnologías, contemplando preguntas sobre uso de dispositivos digitales para ocio y socialización.</p>
<p>Estudios internacionales que contemplan población en la vejez también han medido el uso de tecnologías digitales, como el <em>Programme for the International Assessment of Adult Competencies</em> (PIAAC) realizado por la OCDE. Este incluye preguntas sobre uso de tecnología fuera del trabajo, tanto para ocio, como para comunicarse y socializar, con una muestra de treinta países entre los cuales se encuentra Chile (OECD, 2023).</p>
<p>Otros estudios sobre vejez y salud, como el <em>Health and Retirement Study</em> o el <em>English Longitudinal Study of Ageing</em>, aunque contemplan amplias muestras de adultos mayores con datos panel, solo miden uso a internet de forma dicotómica, impidiendo identificar el ocio y la socialización digital en la población envejecida (Institute for Social Research, 2024; English Longitudinal Study of Ageing, s.f.).}</p>
<p>A continuación, se presenta una tabla de operacionalización de la escala de ocio y socialización digital propuesta.</p>
<section id="escala-de-uso-de-dispositivos-digitales-para-ocio-y-socialización-en-adultos-mayores" class="level3" data-number="3.1"><h3 data-number="3.1" class="anchored" data-anchor-id="escala-de-uso-de-dispositivos-digitales-para-ocio-y-socialización-en-adultos-mayores">
<span class="header-section-number">3.1</span> Escala de uso de dispositivos digitales para ocio y socialización en adultos mayores</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 23%">
<col style="width: 76%">
</colgroup>
<tbody>
<tr class="odd">
<td>Dimensiones</td>
<td>Indicadores</td>
</tr>
<tr class="even">
<td><strong>Uso de dispositivos digitales para la socialización</strong></td>
<td><ul>
<li><p>Frecuencia de uso de dispositivos digitales para enviar mensajes de texto a familiares o amigos (A través de plataformas como Whatsapp o Messenger)</p></li>
<li><p>Frecuencia de uso de dispositivos digitales para realizar videollamadas a familiares o amigos (a través de plataformas como Skype, Whatsapp, Zoom o Meet).</p></li>
<li><p>Frecuencia de uso de dispositivos digitales para participar en grupos o comunidades de redes sociales (a través de plataformas como Facebook o Whatsapp).</p></li>
<li><p>Frecuencia de uso de dispositivos digitales para publicar contenido o interactuar con contenido de otros en redes sociales (a través de plataformas como Facebook, Twitter o Instagram).</p></li>
<li><p>Frecuencia de uso de dispositivos digitales para hacer nuevos amigos o encontrar pareja (a través de plataformas como Facebook, Tinder o Badoo)</p></li>
</ul></td>
</tr>
<tr class="odd">
<td><strong>Uso de dispositivos digitales para el ocio</strong></td>
<td><ul>
<li><p>Frecuencia de uso de dispositivos digitales para escuchar música (a través de plataformas como Spotify o Apple Music).</p></li>
<li><p>Frecuencia de uso de dispositivos digitales para ver videos, series, documentales o películas (a través de plataformas como Youtube, Netflix o Disney +).</p></li>
<li><p>Frecuencia de uso de dispositivos digitales para leer libros, revistas o periódicos.</p></li>
<li><p>Frecuencia de uso de dispositivos digitales para jugar videojuegos.</p></li>
<li><p>Frecuencia de uso de dispositivos digitales para ver videos de corta duración (a través de plataformas como Tiktok, Instagram Reels o Youtube Shorts).</p></li>
</ul></td>
</tr>
</tbody>
</table></section></section><section id="evaluación-de-datos-disponibles-y-propuesta-de-instrumento" class="level2" data-number="4"><h2 data-number="4" class="anchored" data-anchor-id="evaluación-de-datos-disponibles-y-propuesta-de-instrumento">
<span class="header-section-number">4</span> <strong>Evaluación de datos disponibles y propuesta de instrumento</strong>
</h2>
<p>Planteado el constructo teórico, existe la necesidad de medir cada una de estas dimensiones con datos disponibles. Dos estudios son especialmente relevantes. El primero, PIAAC (OECD, 2023), incluye una batería de ítems sobre uso de TIC fuera del trabajo. El encabezado de esta sección es: “Fuera del trabajo. ¿Qué tan frecuentemente usas un computador o un dispositivo digital como una tablet o un smartphone para los siguientes propósitos?” y las categorías de respuesta van de Nunca (1) a Siempre (5). Luego, se presentan una serie de categorías de actividades, con dos que apuntan hacia el ocio y la socialización: comunicarse con otros a través de diferentes medios, y ocio personal (como escuchar música, jugar videojuegos o ver series y películas). Pese a la magnitud de estos datos, caracterizados por un gran muestreo y representatividad en treinta países, tienen dos grandes desventajas en el contexto de este estudio. Primero, la edad máxima de los encuestados es de 65 años, representando sólo a una pequeña porción de los adultos mayores. Segundo, todo el constructo propuesto es medido por dos variables, lo cual no permite capturar la multidimensionalidad de los usos de TIC para el ocio y socialización identificados en la operacionalización del concepto.</p>
<p>Desde el contexto nacional, el estudio ENCVV (Centro de Estudios de Vejez y Envejecimiento UC &amp; Caja Los Andes, 2022) propone un enfoque distinto para medir el uso de TIC en adultos mayores. En su encuesta, incluyen dos preguntas, la primera sobre actividades realizadas a través del uso de un celular inteligente y la segunda desde el internet en general. En la primera, la pregunta corresponde a “Durante el último mes, ¿ha utilizado usted el celular para las siguientes actividades?”, e incluye tareas asociadas al ocio y la socialización, como comunicarse por mensajes o chat, usar redes sociales (como Twitter, Facebook o Instagram), jugar videojuegos y ver videos, series o películas. La segunda pregunta, con el encabezado “Durante el último mes, ¿ha utilizado usted Internet, ya sea a través del celular, computador o tablet, para las siguiente actividades?” Incluye actividades más funcionales, pero también un ítem relacionado con la socialización, sobre videollamadas en medios digitales (como Zoom, Meet o Skype). Pese a la gran cantidad de variables que contempla esta encuesta para medir el uso de TIC para ocio y socialización digital, todas estas se miden de forma dicotómica, permitiendo capturar solo si el encuestado ha realizado la actividad determinada en el último mes o no.</p>
<p>Dadas las limitaciones de ambos estudios disponibles, se propone una forma más precisa de medir los usos de TIC para ocio y socialización en adultos mayores: agregando una mayor cantidad de actividades, como en ENCVV, y, simultáneamente, utilizando escalas Likert de frecuencia, para capturar de mejor manera la variabilidad en los perfiles de uso de TIC para ocio y socialización en la vejez.</p>
<p>Las variables tendrán el siguiente encabezado: “¿Con cuánta frecuencia realiza usted las siguientes actividades a través de dispositivos tecnológicos (como celulares inteligentes, tablets, computadores o laptops). Las categorías de respuesta van desde 1 a 6, donde 1 = Nunca; 2 = Una vez cada varios meses; 3 = Una vez al mes; 4 = Varias veces al mes; 5 = Varias veces a la semana y 6 = Todos los días.&nbsp;</p>
<p>Las actividades que se consultarán coinciden con los indicadores propuestos anteriormente, para socialización: 1. Enviar mensajes de texto a familiares o amigos (a través de plataformas como Whatsapp o Messenger); 2. Realizar videollamadas a familiares o amigos (a través de plataformas como Skype, Zoom o Meet); 3. Participar en grupos o comunidades de redes sociales (a través de plataformas como Facebook o Whatsapp); 4. Publicar contenido o interactuar con contenido de otros en redes sociales (a través de plataformas como Facebook, Twitter o Instagram); y 5. Hacer nuevos amigos o encontrar pareja (a través de plataformas como Facebook, Tinder o Badoo). Para ocio: 1. Escuchar música (a través de plataformas como Spotify o Apple Music); 2. Ver videos, series, documentales o películas (a través de plataformas como Youtube, Netflix o Disney +); 3. Leer libros, revistas o periódicos; 4. Jugar videojuegos; 5. Ver videos de corta duración (a través de plataformas como Tiktok, Instagram Reels o Youtube Shorts).</p>
</section><section id="datos" class="level2" data-number="5"><h2 data-number="5" class="anchored" data-anchor-id="datos">
<span class="header-section-number">5</span> Datos</h2>
<p>En el presente estudio, se utilizarán datos de la ENCVV en su última ola (2022), debido a su pertinencia para evaluar el contexto nacional y diversidad de variables a disposición, y las limitaciones para levantar datos en base al instrumento propuesto. Este estudio comprende un diseño metodológico de tipo transversal y probabilístico. La última realización consta de una muestra total de de 1.786 casos, y es representativa de un 86% de la población mayor de Chile. Por otro lado, dentro de los criterios de exclusión muestrales se encuentran las personas mayores institucionalizadas y personas que por limitaciones cognitivas no puedan responder las preguntas (Centro de Estudios de Vejez y Envejecimiento UC &amp; Caja Los Andes, 2022).</p>
<p>A continuación, se presenta la tabla de operacionalización adaptada según los ítems disponibles en la base de datos:</p>
<section id="escala-de-uso-de-dispositivos-digitales-para-ocio-y-socialización-en-adultos-mayores-adaptada" class="level3" data-number="5.1"><h3 data-number="5.1" class="anchored" data-anchor-id="escala-de-uso-de-dispositivos-digitales-para-ocio-y-socialización-en-adultos-mayores-adaptada">
<span class="header-section-number">5.1</span> Escala de uso de dispositivos digitales para ocio y socialización en adultos mayores adaptada</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 59%">
<col style="width: 40%">
</colgroup>
<tbody>
<tr class="odd">
<td>Dimensiones</td>
<td><strong>Indicadores</strong></td>
</tr>
<tr class="even">
<td>Uso de dispositivos digitales para la socialización</td>
<td>
<p>Hablar con otra persona</p>
<p>Comunicarse por mensajes o chat</p>
<p>Comunicarse por videollamada</p>
<p>Usar Instagram</p>
<p>Usar Twitter</p>
<p>Usar Facebook</p>
<p>Otras redes sociales</p>
<p>Uso de Zoom o Skype</p>
</td>
</tr>
<tr class="odd">
<td>Uso de dispositivos digitales para el ocio</td>
<td>
<p>Leer libros, diarios o revistas</p>
<p>Escuchar música</p>
<p>ver videos, películas o series</p>
<p>Jugar en el celular</p>
<p>Aprender algo a través de internet</p>
<p>Sacar fotos o videos</p>
</td>
</tr>
</tbody>
</table></section><section id="variables-dependientes" class="level3" data-number="5.2"><h3 data-number="5.2" class="anchored" data-anchor-id="variables-dependientes">
<span class="header-section-number">5.2</span> Variables dependientes</h3>
<p>Las variables dependientes corresponden a tres instrumentos validados incluidos en la ENCVV. Aunque la base de datos proporciona variables categorizadas según puntos de corte clínicos, este estudio utilizó los índices sumativos construidos a partir de los ítems originales para preservar la escala de medición completa. Para evaluar la sintomatología depresiva se empleó la Escala de Depresión Geriátrica de Yesavage abreviada (GDS-5) (Hoyl et al., 1999), cuyo puntaje aditivo oscila entre 0 y 5. El sentimiento de soledad fue medido con la Escala UCLA abreviada (Hughes et al., 2004), generando un índice acumulativo con un rango de 0 a 6 puntos. Finalmente, para el aislamiento social se utilizó la Escala de Red Social de Lubben (LSNS-6) (Lubben &amp; Gironda, 2003), la cual entrega un puntaje continuo que varía de 0 a 30 puntos e integra ítems sobre redes familiares y de amistad.</p>
</section><section id="hipótesis" class="level3" data-number="5.3"><h3 data-number="5.3" class="anchored" data-anchor-id="hipótesis">
<span class="header-section-number">5.3</span> Hipótesis</h3>
<p>A partir de las variables disponibles en la base de datos, se plantean las siguientes hipótesis.</p>
<p><span class="math inline">\(H1=\)</span> Los adultos mayores con un mayor índice de uso de dispositivos digitales para ocio y socialización tendrán una menor puntuación en la escala de soledad abreviada UCLA.</p>
<p><span class="math inline">\(H2=\)</span> Los adultos mayores con un mayor índice de uso de dispositivos digitales para ocio y socialización tendrán una mayor puntuación en la escala de redes sociales Lubben.</p>
<p><span class="math inline">\(H3=\)</span> Los adultos mayores con un mayor índice de uso de dispositivos digitales para ocio y socialización tendrán una menor puntuación en la escala de riesgos de síntomas depresivos Yesavage.</p>
</section></section><section id="resultados" class="level2" data-number="6"><h2 data-number="6" class="anchored" data-anchor-id="resultados">
<span class="header-section-number">6</span> Resultados</h2>
<section id="configuración-de-la-sesión" class="level3" data-number="6.1"><h3 data-number="6.1" class="anchored" data-anchor-id="configuración-de-la-sesión">
<span class="header-section-number">6.1</span> Configuración de la sesión</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/install.packages.html">install.packages</a></span><span class="op">(</span><span class="st">"pacman"</span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/trinker/pacman">pacman</a></span><span class="op">)</span></span>
<span><span class="fu">pacman</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/pacman/man/p_load.html">p_load</a></span><span class="op">(</span><span class="va">dplyr</span>, <span class="va">haven</span>, <span class="va">psych</span>, <span class="va">table1</span>, <span class="va">flextable</span>, <span class="va">labelled</span>, <span class="va">forcats</span>, <span class="va">here</span>, <span class="va">corrplot</span>, <span class="va">psy</span>, <span class="va">sjPlot</span><span class="op">)</span> <span class="co"># Descargamos los paquetes</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/options.html">options</a></span><span class="op">(</span>scipen <span class="op">=</span> <span class="fl">999</span><span class="op">)</span> <span class="co"># Desactivar notación científica</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/rm.html">rm</a></span><span class="op">(</span>list <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/ls.html">ls</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span> <span class="co"># Limpiar el entorno de trabajo</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">datos</span> <span class="op">&lt;-</span> <span class="fu">haven</span><span class="fu">::</span><span class="fu"><a href="https://haven.tidyverse.org/reference/read_dta.html">read_dta</a></span><span class="op">(</span><span class="fu">here</span><span class="fu">::</span><span class="fu"><a href="https://here.r-lib.org/reference/here.html">here</a></span><span class="op">(</span><span class="st">"input"</span>, <span class="st">"TendenciaECV20072022publica.dta"</span><span class="op">)</span><span class="op">)</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section><section id="preprocesamiento-de-los-datos" class="level3" data-number="6.2"><h3 data-number="6.2" class="anchored" data-anchor-id="preprocesamiento-de-los-datos">
<span class="header-section-number">6.2</span> Preprocesamiento de los datos</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Filtros a la base de datos original. Seleccionamos variables de interés y año (2022)</span></span>
<span><span class="va">datos_proc</span> <span class="op">&lt;-</span> <span class="va">datos</span> <span class="op">|&gt;</span> </span>
<span>    <span class="fu">select</span><span class="op">(</span><span class="va">AÑO</span>, <span class="va">SEXO</span>, <span class="va">EDAD</span>, <span class="va">EDUCACION</span>, <span class="fu">starts_with</span><span class="op">(</span><span class="st">"TECNOLOGIA1"</span><span class="op">)</span>, <span class="fu">starts_with</span><span class="op">(</span><span class="st">"TECNOLOGIA2"</span><span class="op">)</span>, <span class="va">TECNOLOGIA7_1</span>, <span class="va">TECNOLOGIA7_2</span>, <span class="fu">starts_with</span><span class="op">(</span><span class="st">"LUBBEN"</span><span class="op">)</span>, <span class="fu">starts_with</span><span class="op">(</span><span class="st">"ALONE"</span><span class="op">)</span>, <span class="fu">starts_with</span><span class="op">(</span><span class="st">"DEPRESS"</span><span class="op">)</span>, <span class="op">-</span><span class="va">TECNOLOGIA2_4</span>, <span class="op">-</span><span class="va">TECNOLOGIA2_8</span>, <span class="op">-</span><span class="va">TECNOLOGIA2_9</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>    <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">AÑO</span> <span class="op">==</span> <span class="fl">2022</span><span class="op">)</span></span>
<span></span>
<span><span class="va">variables_categoricas</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"SEXO"</span>, <span class="st">"EDUCACION"</span>, <span class="st">"TECNOLOGIA1"</span>, <span class="st">"TECNOLOGIA2_1"</span>, <span class="st">"TECNOLOGIA2_3"</span>, <span class="st">"TECNOLOGIA2_5"</span>, <span class="st">"TECNOLOGIA2_6"</span>, <span class="st">"TECNOLOGIA2_7"</span>, <span class="st">"TECNOLOGIA2_10"</span>, <span class="st">"TECNOLOGIA2_11"</span>, <span class="st">"TECNOLOGIA2_12"</span>, <span class="st">"TECNOLOGIA2_13"</span>, <span class="st">"TECNOLOGIA2_14"</span>, <span class="st">"TECNOLOGIA2_16"</span>, <span class="st">"TECNOLOGIA2_15"</span>, <span class="st">"TECNOLOGIA7_1"</span>, <span class="st">"TECNOLOGIA7_2"</span>, <span class="st">"LUBBENALTO_"</span>, <span class="st">"ALONE_"</span>, <span class="st">"ALONE2_"</span>, <span class="st">"ALONE1_"</span>, <span class="st">"DEPRESSED_"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Transformamos las variables categóricas a factor para realizar descriptivos adecuados</span></span>
<span></span>
<span><span class="va">datos_proc</span> <span class="op">&lt;-</span> <span class="va">datos_proc</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu">mutate</span><span class="op">(</span>TECNOLOGIA1 <span class="op">=</span> <span class="fu">na_if</span><span class="op">(</span><span class="va">TECNOLOGIA1</span>, <span class="fl">5</span><span class="op">)</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">mutate</span><span class="op">(</span><span class="fu">across</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">TECNOLOGIA7_1</span>, <span class="va">TECNOLOGIA7_2</span><span class="op">)</span>, <span class="op">~</span> <span class="fu">na_if</span><span class="op">(</span><span class="va">.</span>, <span class="fl">3</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu">mutate</span><span class="op">(</span><span class="fu">across</span><span class="op">(</span><span class="fu">all_of</span><span class="op">(</span><span class="va">variables_categoricas</span><span class="op">)</span>, <span class="fu">haven</span><span class="fu">::</span><span class="va"><a href="https://forcats.tidyverse.org/reference/as_factor.html">as_factor</a></span><span class="op">)</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu">mutate</span><span class="op">(</span><span class="fu">across</span><span class="op">(</span><span class="fu">all_of</span><span class="op">(</span><span class="va">variables_categoricas</span><span class="op">)</span>, <span class="va">droplevels</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Codificamos etiquetas de las variables </span></span>
<span></span>
<span><span class="fu">var_label</span><span class="op">(</span><span class="va">datos_proc</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span></span>
<span>  SEXO <span class="op">=</span> <span class="st">"Sexo del entrevistado"</span>,</span>
<span>  EDUCACION <span class="op">=</span> <span class="st">"Nivel educacional"</span>,</span>
<span>  TECNOLOGIA1 <span class="op">=</span> <span class="st">"Tenencia de smartphone"</span>,</span>
<span>  LUBBENALTO_ <span class="op">=</span> <span class="st">"Aislamiento social"</span>,</span>
<span>  ALONE_ <span class="op">=</span> <span class="st">"Soledad autopercibida"</span>,</span>
<span>  DEPRESSED_ <span class="op">=</span> <span class="st">"Riesgo de depresión"</span>,</span>
<span>  TECNOLOGIA2_1 <span class="op">=</span> <span class="st">"Hablar con otra persona"</span>,</span>
<span>  TECNOLOGIA2_3 <span class="op">=</span> <span class="st">"Comunicarse por mensajes o chat"</span>,</span>
<span>  TECNOLOGIA2_5 <span class="op">=</span> <span class="st">"Sacar fotos o videos"</span>,</span>
<span>  TECNOLOGIA2_6 <span class="op">=</span> <span class="st">"Jugar en el celular"</span>,</span>
<span>  TECNOLOGIA2_7 <span class="op">=</span> <span class="st">"Leer libros, diarios o revistas"</span>,</span>
<span>  TECNOLOGIA2_10<span class="op">=</span> <span class="st">"Escuchar música"</span>,</span>
<span>  TECNOLOGIA2_11 <span class="op">=</span> <span class="st">"Ver videos, películas o series"</span>,</span>
<span>  TECNOLOGIA2_12 <span class="op">=</span> <span class="st">"Comunicarse por videollamada"</span>,</span>
<span>  TECNOLOGIA2_13 <span class="op">=</span> <span class="st">"Usar Facebook"</span>,</span>
<span>  TECNOLOGIA2_14 <span class="op">=</span> <span class="st">"Usar Instagram"</span>,</span>
<span>  TECNOLOGIA2_15 <span class="op">=</span> <span class="st">"Usar otras redes sociales"</span>,</span>
<span>  TECNOLOGIA2_16 <span class="op">=</span> <span class="st">"Usar Twitter"</span>,</span>
<span>  TECNOLOGIA7_1 <span class="op">=</span> <span class="st">"Uso de Zoom, Meet o Skype"</span>,</span>
<span>  TECNOLOGIA7_2 <span class="op">=</span> <span class="st">"Aprender algo a través de internet"</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Codificamos etiquetas de las categorías que no venían previamente con la base</span></span>
<span></span>
<span><span class="va">datos_proc</span> <span class="op">&lt;-</span> <span class="va">datos_proc</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu">mutate</span><span class="op">(</span></span>
<span>    <span class="co"># Ejemplo para cambiar una variable específica</span></span>
<span>    LUBBENALTO_ <span class="op">=</span> <span class="fu">fct_recode</span><span class="op">(</span><span class="va">LUBBENALTO_</span>,</span>
<span>      <span class="st">"Bajo o nulo riesgo de aislamiento social"</span> <span class="op">=</span> <span class="st">"0"</span>,</span>
<span>      <span class="st">"Alto riesgo de aislamiento social"</span> <span class="op">=</span> <span class="st">"1"</span></span>
<span>    <span class="op">)</span>,</span>
<span>    </span>
<span>    DEPRESSED_ <span class="op">=</span> <span class="fu">fct_recode</span><span class="op">(</span><span class="va">DEPRESSED_</span>,</span>
<span>      <span class="st">"Sin sospecha de depresión"</span> <span class="op">=</span> <span class="st">"0"</span>,</span>
<span>      <span class="st">"Sospecha de síntomas depresivos"</span> <span class="op">=</span> <span class="st">"1"</span></span>
<span>    <span class="op">)</span></span>
<span>  <span class="op">)</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section><section id="resultados-descriptivos" class="level3" data-number="6.3"><h3 data-number="6.3" class="anchored" data-anchor-id="resultados-descriptivos">
<span class="header-section-number">6.3</span> Resultados descriptivos</h3>
<section id="descriptivos-de-la-muestra" class="level4" data-number="6.3.1"><h4 data-number="6.3.1" class="anchored" data-anchor-id="descriptivos-de-la-muestra">
<span class="header-section-number">6.3.1</span> Descriptivos de la muestra</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">table1</span><span class="op">(</span><span class="op">~</span> <span class="va">SEXO</span> <span class="op">+</span> <span class="va">EDAD</span> <span class="op">+</span> <span class="va">EDUCACION</span> <span class="op">+</span> <span class="va">TECNOLOGIA1</span> <span class="op">+</span> <span class="va">LUBBENALTO_</span> <span class="op">+</span> <span class="va">ALONE_</span> <span class="op">+</span> <span class="va">DEPRESSED_</span>, data <span class="op">=</span> <span class="va">datos_proc</span>, caption <span class="op">=</span> <span class="st">"Descriptivos generales de la muestra"</span>, footnote <span class="op">=</span> <span class="st">"Elaboración propia con datos de la ECVV 2022"</span><span class="op">)</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="Rtable1"><table class="Rtable1">
<caption>Descriptivos generales de la muestra</caption>

<thead><tr>
<th class="rowlabel firstrow lastrow"></th>
<th class="firstrow lastrow"><span class="stratlabel">Overall<br><span class="stratn">(N=1789)</span></span></th>
</tr></thead>
<tfoot><tr><td colspan="2" class="Rtable1-footnote">
<p>Elaboración propia con datos de la ECVV 2022</p>
</td></tr></tfoot>
<tbody>
<tr>
<td class="rowlabel firstrow">Sexo del entrevistado</td>
<td class="firstrow"></td>
</tr>
<tr>
<td class="rowlabel">Hombre</td>
<td>592 (33.1%)</td>
</tr>
<tr>
<td class="rowlabel lastrow">Mujer</td>
<td class="lastrow">1197 (66.9%)</td>
</tr>
<tr>
<td class="rowlabel firstrow">¿Cuál es su edad (en años)?</td>
<td class="firstrow"></td>
</tr>
<tr>
<td class="rowlabel">Mean (SD)</td>
<td>71.2 (8.03)</td>
</tr>
<tr>
<td class="rowlabel lastrow">Median [Min, Max]</td>
<td class="lastrow">70.0 [60.0, 98.0]</td>
</tr>
<tr>
<td class="rowlabel firstrow">Nivel educacional</td>
<td class="firstrow"></td>
</tr>
<tr>
<td class="rowlabel">Sin estudios</td>
<td>84 (4.7%)</td>
</tr>
<tr>
<td class="rowlabel">Básica o preparatoria completa o incompleta</td>
<td>687 (38.4%)</td>
</tr>
<tr>
<td class="rowlabel">Humanidades o educación media completa o incompleta</td>
<td>668 (37.3%)</td>
</tr>
<tr>
<td class="rowlabel">Educación técnica, comercial o normalista</td>
<td>194 (10.8%)</td>
</tr>
<tr>
<td class="rowlabel lastrow">Educación universitaria completa o incompleta</td>
<td class="lastrow">156 (8.7%)</td>
</tr>
<tr>
<td class="rowlabel firstrow">Tenencia de smartphone</td>
<td class="firstrow"></td>
</tr>
<tr>
<td class="rowlabel">Sí, es un Smartphone</td>
<td>874 (48.9%)</td>
</tr>
<tr>
<td class="rowlabel">Sí, un celular convencional</td>
<td>429 (24.0%)</td>
</tr>
<tr>
<td class="rowlabel">Sí tiene celular pero no sabe de qué tipo</td>
<td>269 (15.0%)</td>
</tr>
<tr>
<td class="rowlabel">No tiene celular</td>
<td>211 (11.8%)</td>
</tr>
<tr>
<td class="rowlabel lastrow">Missing</td>
<td class="lastrow">6 (0.3%)</td>
</tr>
<tr>
<td class="rowlabel firstrow">Aislamiento social</td>
<td class="firstrow"></td>
</tr>
<tr>
<td class="rowlabel">Bajo o nulo riesgo de aislamiento social</td>
<td>788 (44.0%)</td>
</tr>
<tr>
<td class="rowlabel">Alto riesgo de aislamiento social</td>
<td>988 (55.2%)</td>
</tr>
<tr>
<td class="rowlabel lastrow">Missing</td>
<td class="lastrow">13 (0.7%)</td>
</tr>
<tr>
<td class="rowlabel firstrow">Soledad autopercibida</td>
<td class="firstrow"></td>
</tr>
<tr>
<td class="rowlabel">SinSoledad</td>
<td>873 (48.8%)</td>
</tr>
<tr>
<td class="rowlabel">ConSoledad</td>
<td>909 (50.8%)</td>
</tr>
<tr>
<td class="rowlabel lastrow">Missing</td>
<td class="lastrow">7 (0.4%)</td>
</tr>
<tr>
<td class="rowlabel firstrow">Riesgo de depresión</td>
<td class="firstrow"></td>
</tr>
<tr>
<td class="rowlabel">Sin sospecha de depresión</td>
<td>1184 (66.2%)</td>
</tr>
<tr>
<td class="rowlabel">Sospecha de síntomas depresivos</td>
<td>604 (33.8%)</td>
</tr>
<tr>
<td class="rowlabel lastrow">Missing</td>
<td class="lastrow">1 (0.1%)</td>
</tr>
</tbody>
</table></div>
</div>
</div>
<p>Con respecto a las características de la muestra, el promedio de edad es de 71.2 años (DE = 8.03), y se observa una mayor presencia de mujeres (66.9%). Los niveles educacionales más comunes son Básica o preparatoria completa o incompleta (38.4%) y Humanidades o educación media completa o incompleta (37.3%). Alrededor de la mitad de los adultos mayores encuestados reportan tener un teléfono inteligente, y un cuarto de estos un celular convencional. Sobre las variables dependientes del estudio, más de la mitad de la muestra presenta un alto riesgo de aislamiento social, se autopercibe con un nivel considerable de soledad, y aproximadamente un tercio de los individuos presenta síntomas depresivos.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">items_seleccionados</span> <span class="op">&lt;-</span> <span class="va">datos_proc</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu">select</span><span class="op">(</span><span class="va">TECNOLOGIA2_1</span>, <span class="va">TECNOLOGIA2_3</span>, </span>
<span>         <span class="va">TECNOLOGIA2_5</span>, <span class="va">TECNOLOGIA2_6</span>, <span class="va">TECNOLOGIA2_7</span>, <span class="va">TECNOLOGIA2_10</span>, <span class="va">TECNOLOGIA2_11</span>, <span class="va">TECNOLOGIA2_12</span>, </span>
<span>         <span class="va">TECNOLOGIA2_13</span>, <span class="va">TECNOLOGIA2_14</span>, <span class="va">TECNOLOGIA2_16</span>, <span class="va">TECNOLOGIA2_15</span>, </span>
<span>         <span class="va">TECNOLOGIA7_1</span>, <span class="va">TECNOLOGIA7_2</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># 2. Ahora aplicamos la función sobre ese objeto</span></span>
<span><span class="fu">table1</span><span class="op">(</span><span class="op">~</span><span class="va">.</span>,data<span class="op">=</span><span class="va">items_seleccionados</span>, caption <span class="op">=</span> <span class="st">'"Ha utilizado el celular para..."'</span><span class="op">)</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="Rtable1">
<table class="Rtable1 caption-top table table-sm table-striped small">
<caption>"Ha utilizado el celular para..."</caption>
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead><tr class="header">
<th class="rowlabel firstrow lastrow" data-quarto-table-cell-role="th"></th>
<th class="firstrow lastrow" data-quarto-table-cell-role="th"><span class="stratlabel">Overall<br><span class="stratn">(N=1789)</span></span></th>
</tr></thead>
<tbody>
<tr class="odd">
<td class="rowlabel firstrow">Hablar con otra persona</td>
<td class="firstrow"></td>
</tr>
<tr class="even">
<td class="rowlabel">Si</td>
<td>1607 (89.8%)</td>
</tr>
<tr class="odd">
<td class="rowlabel">No</td>
<td>173 (9.7%)</td>
</tr>
<tr class="even">
<td class="rowlabel lastrow">Missing</td>
<td class="lastrow">9 (0.5%)</td>
</tr>
<tr class="odd">
<td class="rowlabel firstrow">Comunicarse por mensajes o chat</td>
<td class="firstrow"></td>
</tr>
<tr class="even">
<td class="rowlabel">Si</td>
<td>1025 (57.3%)</td>
</tr>
<tr class="odd">
<td class="rowlabel">No</td>
<td>748 (41.8%)</td>
</tr>
<tr class="even">
<td class="rowlabel lastrow">Missing</td>
<td class="lastrow">16 (0.9%)</td>
</tr>
<tr class="odd">
<td class="rowlabel firstrow">Sacar fotos o videos</td>
<td class="firstrow"></td>
</tr>
<tr class="even">
<td class="rowlabel">Si</td>
<td>848 (47.4%)</td>
</tr>
<tr class="odd">
<td class="rowlabel">No</td>
<td>914 (51.1%)</td>
</tr>
<tr class="even">
<td class="rowlabel lastrow">Missing</td>
<td class="lastrow">27 (1.5%)</td>
</tr>
<tr class="odd">
<td class="rowlabel firstrow">Jugar en el celular</td>
<td class="firstrow"></td>
</tr>
<tr class="even">
<td class="rowlabel">Sí</td>
<td>461 (25.8%)</td>
</tr>
<tr class="odd">
<td class="rowlabel">No</td>
<td>1311 (73.3%)</td>
</tr>
<tr class="even">
<td class="rowlabel lastrow">Missing</td>
<td class="lastrow">17 (1.0%)</td>
</tr>
<tr class="odd">
<td class="rowlabel firstrow">Leer libros, diarios o revistas</td>
<td class="firstrow"></td>
</tr>
<tr class="even">
<td class="rowlabel">Sí</td>
<td>365 (20.4%)</td>
</tr>
<tr class="odd">
<td class="rowlabel">No</td>
<td>1399 (78.2%)</td>
</tr>
<tr class="even">
<td class="rowlabel lastrow">Missing</td>
<td class="lastrow">25 (1.4%)</td>
</tr>
<tr class="odd">
<td class="rowlabel firstrow">Escuchar música</td>
<td class="firstrow"></td>
</tr>
<tr class="even">
<td class="rowlabel">Sí</td>
<td>548 (30.6%)</td>
</tr>
<tr class="odd">
<td class="rowlabel">No</td>
<td>1217 (68.0%)</td>
</tr>
<tr class="even">
<td class="rowlabel lastrow">Missing</td>
<td class="lastrow">24 (1.3%)</td>
</tr>
<tr class="odd">
<td class="rowlabel firstrow">Ver videos, películas o series</td>
<td class="firstrow"></td>
</tr>
<tr class="even">
<td class="rowlabel">Sí</td>
<td>379 (21.2%)</td>
</tr>
<tr class="odd">
<td class="rowlabel">No</td>
<td>1393 (77.9%)</td>
</tr>
<tr class="even">
<td class="rowlabel lastrow">Missing</td>
<td class="lastrow">17 (1.0%)</td>
</tr>
<tr class="odd">
<td class="rowlabel firstrow">Comunicarse por videollamada</td>
<td class="firstrow"></td>
</tr>
<tr class="even">
<td class="rowlabel">Sí</td>
<td>880 (49.2%)</td>
</tr>
<tr class="odd">
<td class="rowlabel">No</td>
<td>882 (49.3%)</td>
</tr>
<tr class="even">
<td class="rowlabel lastrow">Missing</td>
<td class="lastrow">27 (1.5%)</td>
</tr>
<tr class="odd">
<td class="rowlabel firstrow">Usar Facebook</td>
<td class="firstrow"></td>
</tr>
<tr class="even">
<td class="rowlabel">Sí</td>
<td>730 (40.8%)</td>
</tr>
<tr class="odd">
<td class="rowlabel">No</td>
<td>1040 (58.1%)</td>
</tr>
<tr class="even">
<td class="rowlabel lastrow">Missing</td>
<td class="lastrow">19 (1.1%)</td>
</tr>
<tr class="odd">
<td class="rowlabel firstrow">Usar Instagram</td>
<td class="firstrow"></td>
</tr>
<tr class="even">
<td class="rowlabel">Sí</td>
<td>288 (16.1%)</td>
</tr>
<tr class="odd">
<td class="rowlabel">No</td>
<td>1478 (82.6%)</td>
</tr>
<tr class="even">
<td class="rowlabel lastrow">Missing</td>
<td class="lastrow">23 (1.3%)</td>
</tr>
<tr class="odd">
<td class="rowlabel firstrow">Usar Twitter</td>
<td class="firstrow"></td>
</tr>
<tr class="even">
<td class="rowlabel">Sí</td>
<td>122 (6.8%)</td>
</tr>
<tr class="odd">
<td class="rowlabel">No</td>
<td>1646 (92.0%)</td>
</tr>
<tr class="even">
<td class="rowlabel lastrow">Missing</td>
<td class="lastrow">21 (1.2%)</td>
</tr>
<tr class="odd">
<td class="rowlabel firstrow">Usar otras redes sociales</td>
<td class="firstrow"></td>
</tr>
<tr class="even">
<td class="rowlabel">Sí</td>
<td>181 (10.1%)</td>
</tr>
<tr class="odd">
<td class="rowlabel">No</td>
<td>1587 (88.7%)</td>
</tr>
<tr class="even">
<td class="rowlabel lastrow">Missing</td>
<td class="lastrow">21 (1.2%)</td>
</tr>
<tr class="odd">
<td class="rowlabel firstrow">Uso de Zoom, Meet o Skype</td>
<td class="firstrow"></td>
</tr>
<tr class="even">
<td class="rowlabel">Sí</td>
<td>208 (11.6%)</td>
</tr>
<tr class="odd">
<td class="rowlabel">No</td>
<td>1553 (86.8%)</td>
</tr>
<tr class="even">
<td class="rowlabel lastrow">Missing</td>
<td class="lastrow">28 (1.6%)</td>
</tr>
<tr class="odd">
<td class="rowlabel firstrow">Aprender algo a través de internet</td>
<td class="firstrow"></td>
</tr>
<tr class="even">
<td class="rowlabel">Sí</td>
<td>361 (20.2%)</td>
</tr>
<tr class="odd">
<td class="rowlabel">No</td>
<td>1407 (78.6%)</td>
</tr>
<tr class="even">
<td class="rowlabel lastrow">Missing</td>
<td class="lastrow">21 (1.2%)</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Sobre las variables que componen la operacionalización realizada, el uso de celulares más reportado por los individuos es para hablar con otra persona (89.8%), seguido de comunicarse por mensajes o chat en plataformas como WhatsApp (57.3%) y comunicarse por videollamada (49.2%). Facebook es la red social que más utilizan los adultos mayores que componen la muestra (40.8%), con una gran diferencia con la segunda más utilizada que es Instagram (16.1%). Dos de las variables consideradas no se reducen al uso a través del celular, y presentan una menor frecuencia que las demás: Uso de Zoom, Meet o Skype (11.6%) y Aprender algo a través de internet (20.2%).</p>
</section></section><section id="validación-de-la-escala" class="level3" data-number="6.4"><h3 data-number="6.4" class="anchored" data-anchor-id="validación-de-la-escala">
<span class="header-section-number">6.4</span> Validación de la escala</h3>
<section id="matriz-de-correlaciones" class="level4" data-number="6.4.1"><h4 data-number="6.4.1" class="anchored" data-anchor-id="matriz-de-correlaciones">
<span class="header-section-number">6.4.1</span> Matriz de correlaciones</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">vars_indice</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"TECNOLOGIA2_1"</span>, <span class="st">"TECNOLOGIA2_3"</span>, <span class="st">"TECNOLOGIA2_5"</span>, </span>
<span>                 <span class="st">"TECNOLOGIA2_6"</span>, <span class="st">"TECNOLOGIA2_7"</span>, <span class="st">"TECNOLOGIA2_10"</span>, </span>
<span>                 <span class="st">"TECNOLOGIA2_11"</span>, <span class="st">"TECNOLOGIA2_12"</span>, <span class="st">"TECNOLOGIA2_13"</span>, </span>
<span>                 <span class="st">"TECNOLOGIA2_14"</span>, <span class="st">"TECNOLOGIA2_16"</span>, <span class="st">"TECNOLOGIA2_15"</span>, </span>
<span>                 <span class="st">"TECNOLOGIA7_1"</span>, <span class="st">"TECNOLOGIA7_2"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">tech_data</span> <span class="op">&lt;-</span> <span class="va">datos</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">AÑO</span> <span class="op">==</span> <span class="fl">2022</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu">select</span><span class="op">(</span><span class="va">TECNOLOGIA2_1</span>, <span class="va">TECNOLOGIA2_3</span>, </span>
<span>         <span class="va">TECNOLOGIA2_5</span>, <span class="va">TECNOLOGIA2_6</span>, <span class="va">TECNOLOGIA2_7</span>, <span class="va">TECNOLOGIA2_10</span>, <span class="va">TECNOLOGIA2_11</span>, <span class="va">TECNOLOGIA2_12</span>, </span>
<span>         <span class="va">TECNOLOGIA2_13</span>, <span class="va">TECNOLOGIA2_14</span>, <span class="va">TECNOLOGIA2_16</span>, <span class="va">TECNOLOGIA2_15</span>, </span>
<span>         <span class="va">TECNOLOGIA7_1</span>, <span class="va">TECNOLOGIA7_2</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">mutate</span><span class="op">(</span><span class="fu">across</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">TECNOLOGIA7_1</span>, <span class="va">TECNOLOGIA7_2</span><span class="op">)</span>, <span class="op">~</span> <span class="fu">na_if</span><span class="op">(</span><span class="va">.</span>, <span class="fl">3</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">mutate</span><span class="op">(</span><span class="fu">across</span><span class="op">(</span><span class="fu">all_of</span><span class="op">(</span><span class="va">vars_indice</span><span class="op">)</span>, <span class="op">~</span> <span class="fl">2</span> <span class="op">-</span> <span class="va">.</span><span class="op">)</span><span class="op">)</span> <span class="co"># Se restan los puntajes a 2 para invertir el índice (en el que 1 significa si y 2 significa no) y que el puntaje mínimo sea 0</span></span>
<span></span>
<span><span class="fu">var_label</span><span class="op">(</span><span class="va">tech_data</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span></span>
<span>  TECNOLOGIA2_1 <span class="op">=</span> <span class="st">"Hablar con otra persona"</span>,</span>
<span>  TECNOLOGIA2_3 <span class="op">=</span> <span class="st">"Comunicarse por mensajes o chat"</span>,</span>
<span>  TECNOLOGIA2_5 <span class="op">=</span> <span class="st">"Sacar fotos o videos"</span>,</span>
<span>  TECNOLOGIA2_6 <span class="op">=</span> <span class="st">"Jugar en el celular"</span>,</span>
<span>  TECNOLOGIA2_7 <span class="op">=</span> <span class="st">"Leer libros, diarios o revistas"</span>,</span>
<span>  TECNOLOGIA2_10<span class="op">=</span> <span class="st">"Escuchar música"</span>,</span>
<span>  TECNOLOGIA2_11 <span class="op">=</span> <span class="st">"Ver videos, películas o series"</span>,</span>
<span>  TECNOLOGIA2_12 <span class="op">=</span> <span class="st">"Comunicarse por videollamada"</span>,</span>
<span>  TECNOLOGIA2_13 <span class="op">=</span> <span class="st">"Usar Facebook"</span>,</span>
<span>  TECNOLOGIA2_14 <span class="op">=</span> <span class="st">"Usar Instagram"</span>,</span>
<span>  TECNOLOGIA2_15 <span class="op">=</span> <span class="st">"Usar otras redes sociales"</span>,</span>
<span>  TECNOLOGIA2_16 <span class="op">=</span> <span class="st">"Usar Twitter"</span>,</span>
<span>  TECNOLOGIA7_1 <span class="op">=</span> <span class="st">"Uso de Zoom, Meet o Skype"</span>,</span>
<span>  TECNOLOGIA7_2 <span class="op">=</span> <span class="st">"Aprender algo a través de internet"</span></span>
<span><span class="op">)</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">nombres_cortos</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span></span>
<span>  <span class="st">"Llamadas"</span>,       <span class="co"># T2_1: Hablar con otra persona</span></span>
<span>  <span class="st">"Chat/Msj"</span>,       <span class="co"># T2_3: Comunicarse por mensajes</span></span>
<span>  <span class="st">"Camara"</span>,         <span class="co"># T2_5: Sacar fotos/videos</span></span>
<span>  <span class="st">"Juegos"</span>,         <span class="co"># T2_6: Jugar</span></span>
<span>  <span class="st">"Leer"</span>,           <span class="co"># T2_7: Leer libros/diarios</span></span>
<span>  <span class="st">"Música"</span>,         <span class="co"># T2_10: Escuchar música</span></span>
<span>  <span class="st">"Videos/TV"</span>,      <span class="co"># T2_11: Ver videos/series</span></span>
<span>  <span class="st">"Videollamada"</span>,   <span class="co"># T2_12: Comunicarse por videollamada (Personal)</span></span>
<span>  <span class="st">"Facebook"</span>,       <span class="co"># T2_13</span></span>
<span>  <span class="st">"Instagram"</span>,      <span class="co"># T2_14</span></span>
<span>  <span class="st">"Twitter/X"</span>,      <span class="co"># T2_16</span></span>
<span>  <span class="st">"Otras RRSS"</span>,     <span class="co"># T2_15</span></span>
<span>  <span class="st">"Zoom/Reunión"</span>,   <span class="co"># T7_1: Uso de Zoom/Meet (Más formal/trabajo)</span></span>
<span>  <span class="st">"Aprender"</span>        <span class="co"># T7_2: Aprender por internet</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="va">matCor</span> <span class="op">&lt;-</span> <span class="fu">tetrachoric</span><span class="op">(</span><span class="va">tech_data</span><span class="op">)</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/colnames.html">rownames</a></span><span class="op">(</span><span class="va">matCor</span><span class="op">$</span><span class="va">rho</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="va">nombres_cortos</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/colnames.html">colnames</a></span><span class="op">(</span><span class="va">matCor</span><span class="op">$</span><span class="va">rho</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="va">nombres_cortos</span></span>
<span></span>
<span><span class="fu">corrplot</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/corrplot/man/corrplot.html">corrplot</a></span><span class="op">(</span><span class="va">matCor</span><span class="op">$</span><span class="va">rho</span>, </span>
<span>                   method <span class="op">=</span> <span class="st">"number"</span>, </span>
<span>                   type <span class="op">=</span> <span class="st">"lower"</span>,</span>
<span>                   tl.cex <span class="op">=</span> <span class="fl">0.7</span>,</span>
<span>                   number.cex <span class="op">=</span> <span class="fl">0.8</span>,</span>
<span>                   tl.col <span class="op">=</span> <span class="st">"black"</span>,</span>
<span>                   diag <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="an%C3%A1lisis_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p>Como primer paso del análisis, se estimó una matriz de correlaciones tetracórica, debido a la naturaleza dicotómica de todas las variables que componen la batería de uso de dispositivos digitales en la ENCVV 2022. Todas las correlaciones son positivas, con una magnitud alta en la mayoría de casos, y moderada en una menor proporción de ítems. El rango de las magnitudes varía entre 0.4 y 0.89, siendo la menor correlación registrada la correspondiente a los ítems de utilización de dispositivos digitales para hablar con otras personas y consumir contenido audiovisual.</p>
</section><section id="análisis-factorial-exploratorio" class="level4" data-number="6.4.2"><h4 data-number="6.4.2" class="anchored" data-anchor-id="análisis-factorial-exploratorio">
<span class="header-section-number">6.4.2</span> Análisis Factorial Exploratorio</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">KMO</span><span class="op">(</span><span class="va">matCor</span><span class="op">$</span><span class="va">rho</span><span class="op">)</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Kaiser-Meyer-Olkin factor adequacy
Call: KMO(r = matCor$rho)
Overall MSA =  0.87
MSA for each item = 
    Llamadas     Chat/Msj       Camara       Juegos         Leer       Música 
        0.83         0.86         0.94         0.95         0.93         0.93 
   Videos/TV Videollamada     Facebook    Instagram    Twitter/X   Otras RRSS 
        0.86         0.81         0.94         0.90         0.81         0.86 
Zoom/Reunión     Aprender 
        0.80         0.82 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">cortest.bartlett</span><span class="op">(</span><span class="va">matCor</span><span class="op">$</span><span class="va">rho</span>, n <span class="op">=</span> <span class="fl">1789</span><span class="op">)</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>$chisq
[1] 29098.67

$p.value
[1] 0

$df
[1] 91</code></pre>
</div>
</div>
<p>Para analizar si un Análisis Factorial Exploratorio (AFE) es plausible en la muestra, se realizaron dos análisis: el test de KMO y el test de esfericidad de Barlett. El valor KMO de la matriz de correlaciones es satisfactorio (&gt;0.8), lo cual indica que probablemente los datos sean idóneos para conducir un AFE, coincidente con el resultado significativo del test de esfericidad de Barlett (<span class="math inline">\(\chi^2\)</span>=29098; p&lt;0.001).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb13"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">scree.plot</span><span class="op">(</span><span class="va">tech_data</span><span class="op">)</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="an%C3%A1lisis_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">fa.parallel</span><span class="op">(</span><span class="va">matCor</span><span class="op">$</span><span class="va">rho</span>, n.obs<span class="op">=</span><span class="fl">1789</span>, fa<span class="op">=</span><span class="st">"fa"</span><span class="op">)</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="an%C3%A1lisis_files/figure-html/unnamed-chunk-9-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Parallel analysis suggests that the number of factors =  6  and the number of components =  NA </code></pre>
</div>
</div>
<p>Luego, se realizaron dos pruebas para determinar la cantidad de factores óptimos para estimar el AFE. Primero, el análisis del gráfico de sedimentación indica que podrían estimarse uno, dos o tres factores, ya que la recta se vuelve más empinada a partir de las cuatro dimensiones. La observación del análisis paralelo de Horn sugiere algo similar, los dos primeros factores se ubican por encima de la recta simulada, mientras que el tercero está muy ligeramente sobre esta. Debido a esto, se realizará el AFE con dos factores, acorde con la operacionalización realizada anteriormente. Si los resultados de este no muestran un sustento teórico relevante, agrupando ítems muy distintos entre sí, o el ajuste es muy pobre (observando las cargas factoriales y los indicadores relevantes), se continuará con un modelo unidimensional o uno tridimensional.</p>
<p>Los modelos serán estimados utilizando matrices de correlación tetracóricas, que es lo adecuado debido al nivel de medición de los ítems. Se utilizará la rotación oblimin, ya que al ser oblicua permite la correlación entre factores, y el estimador PA, dado que no asume normalidad multivariada.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">modelo_2f</span> <span class="op">&lt;-</span> <span class="fu">fa</span><span class="op">(</span></span>
<span>  r <span class="op">=</span> <span class="va">tech_data</span>, </span>
<span>  nfactors <span class="op">=</span> <span class="fl">2</span>, </span>
<span>  rotate <span class="op">=</span> <span class="st">"oblimin"</span>,</span>
<span>  fm <span class="op">=</span> <span class="st">"pa"</span>, </span>
<span>  cor <span class="op">=</span> <span class="st">"tet"</span></span>
<span><span class="op">)</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb17"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">sjPlot</span><span class="fu">::</span><span class="fu"><a href="https://strengejacke.github.io/sjPlot/reference/tab_fa.html">tab_fa</a></span><span class="op">(</span></span>
<span>  <span class="va">modelo_2f</span>,</span>
<span>  title <span class="op">=</span> <span class="st">"Cargas factoriales AFE 2 factores"</span>,</span>
<span>  sort <span class="op">=</span> <span class="cn">TRUE</span>,</span>
<span>  fctr.load.tlrn <span class="op">=</span> <span class="fl">0.2</span>,</span>
<span>  var.labels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Hablar con otra persona"</span>, </span>
<span>  <span class="st">"Comunicarse por mensajes o chat"</span>, </span>
<span>  <span class="st">"Sacar fotos o videos"</span>,</span>
<span>  <span class="st">"Jugar en el celular"</span>,</span>
<span>  <span class="st">"Leer libros, diarios o revistas"</span>,</span>
<span>  <span class="st">"Escuchar música"</span>,</span>
<span>  <span class="st">"Ver videos, películas o series"</span>,</span>
<span>  <span class="st">"Comunicarse por videollamada"</span>,</span>
<span>  <span class="st">"Usar Facebook"</span>,</span>
<span>  <span class="st">"Usar Instagram"</span>,</span>
<span>  <span class="st">"Usar Twitter"</span>,</span>
<span>  <span class="st">"Usar otras redes sociales"</span>,</span>
<span>  <span class="st">"Uso de Zoom, Meet o Skype"</span>,</span>
<span>  <span class="st">"Aprender algo a través de internet"</span></span>
<span>  <span class="op">)</span></span>
<span>  <span class="op">)</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Cargas factoriales AFE 2 factores</caption>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th" style="border-top: double black; padding: 0.2cm">&nbsp;</th>
<th data-quarto-table-cell-role="th" style="border-top: double black; padding: 0.2cm">Factor 1</th>
<th data-quarto-table-cell-role="th" style="border-top: double black; padding: 0.2cm">Factor 2</th>
</tr>
<tr class="even">
<td style="border-top: 1px solid black">Usar Facebook</td>
<td style="text-align: center; padding: 0.2cm; border-top: 1px solid black;">0.99</td>
<td style="text-align: center; padding: 0.2cm; color: #cccccc; border-top: 1px solid black;">-0.05</td>
</tr>
<tr class="odd">
<td>Usar Instagram</td>
<td style="text-align: center; padding: 0.2cm;">0.92</td>
<td style="text-align: center; padding: 0.2cm; color: #cccccc;">-0.03</td>
</tr>
<tr class="even">
<td>Usar Twitter</td>
<td style="text-align: center; padding: 0.2cm;">0.84</td>
<td style="text-align: center; padding: 0.2cm; color: #cccccc;">-0.07</td>
</tr>
<tr class="odd">
<td>Hablar con otra persona</td>
<td style="text-align: center; padding: 0.2cm;">0.81</td>
<td style="text-align: center; padding: 0.2cm; color: #cccccc;">-0.06</td>
</tr>
<tr class="even">
<td>Comunicarse por mensajes o chat</td>
<td style="text-align: center; padding: 0.2cm;">0.75</td>
<td style="text-align: center; padding: 0.2cm; color: #cccccc;">0.25</td>
</tr>
<tr class="odd">
<td>Usar otras redes sociales</td>
<td style="text-align: center; padding: 0.2cm;">0.73</td>
<td style="text-align: center; padding: 0.2cm; color: #cccccc;">-0.01</td>
</tr>
<tr class="even">
<td>Comunicarse por videollamada</td>
<td style="text-align: center; padding: 0.2cm;">0.70</td>
<td style="text-align: center; padding: 0.2cm; color: #cccccc;">0.23</td>
</tr>
<tr class="odd">
<td style="background-color: #eacccc">Sacar fotos o videos</td>
<td style="text-align: center; padding: 0.2cm; background-color: #eacccc;">0.55</td>
<td style="text-align: center; padding: 0.2cm; color: #cccccc; background-color: #eacccc;">0.38</td>
</tr>
<tr class="even">
<td>Ver videos, películas o series</td>
<td style="text-align: center; padding: 0.2cm; color: #cccccc;">-0.07</td>
<td style="text-align: center; padding: 0.2cm;">0.88</td>
</tr>
<tr class="odd">
<td>Escuchar música</td>
<td style="text-align: center; padding: 0.2cm; color: #cccccc;">0.02</td>
<td style="text-align: center; padding: 0.2cm;">0.84</td>
</tr>
<tr class="even">
<td>Aprender algo a través de internet</td>
<td style="text-align: center; padding: 0.2cm; color: #cccccc;">0.04</td>
<td style="text-align: center; padding: 0.2cm;">0.79</td>
</tr>
<tr class="odd">
<td>Uso de Zoom, Meet o Skype</td>
<td style="text-align: center; padding: 0.2cm; color: #cccccc;">0.05</td>
<td style="text-align: center; padding: 0.2cm;">0.77</td>
</tr>
<tr class="even">
<td>Leer libros, diarios o revistas</td>
<td style="text-align: center; padding: 0.2cm; color: #cccccc;">0.13</td>
<td style="text-align: center; padding: 0.2cm;">0.65</td>
</tr>
<tr class="odd">
<td style="background-color: #eacccc">Jugar en el celular</td>
<td style="text-align: center; padding: 0.2cm; color: #cccccc; background-color: #eacccc;">0.38</td>
<td style="text-align: center; padding: 0.2cm; background-color: #eacccc;">0.43</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Analizando las cargas factoriales, se observa una estructura similar a la proyectada en la operacionalización del concepto. Por el lado del primer factor, se agrupan los ítems relacionados a la socialización, cómo la interacción en redes sociales o la comunicación directa a través de mensajes o videollamadas, por lo que se denomina esta dimensión “Uso de dispositivos digitales para socialización”. En el segundo factor, se encuentran actividades vinculadas con el ocio y el entretenimiento que pueden ser desarrolladas en solitario, cómo leer libros, escuchar música o ver películas o series, por lo que se denomina esta dimensión “Uso de dispositivos digitales para ocio y entretenimiento”. Llamativamente, la variable de videollamadas a través de Zoom o Meet presentó una carga alta en este segundo factor, tal vez porque los encuestados asocian estas plataformas a tareas educativas o informativas, más que a la comunicación interpersonal. Dos ítems presentaron cargas cruzadas de una magnitud que no se puede ignorar (&lt;0.3), y una diferencia entre las cargas hacia ambas dimensiones de menos de 0.2: “Jugar en el celular” y “Sacar fotos o videos”. Debido a su carácter ambiguo y gracias a disponer de suficientes variables para estimar cada factor, se decide descartar estos ítems de la construcción de los índices y del modelo final.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">tech_data_2</span> <span class="op">&lt;-</span> <span class="va">tech_data</span> <span class="op">|&gt;</span> <span class="fu">select</span><span class="op">(</span><span class="op">-</span><span class="va">TECNOLOGIA2_6</span>, <span class="op">-</span><span class="va">TECNOLOGIA2_5</span><span class="op">)</span></span>
<span><span class="va">modelo_2f_2</span> <span class="op">&lt;-</span> <span class="fu">fa</span><span class="op">(</span></span>
<span>  r <span class="op">=</span> <span class="va">tech_data_2</span>, </span>
<span>  nfactors <span class="op">=</span> <span class="fl">2</span>, </span>
<span>  rotate <span class="op">=</span> <span class="st">"oblimin"</span>,</span>
<span>  fm <span class="op">=</span> <span class="st">"pa"</span>, </span>
<span>  cor <span class="op">=</span> <span class="st">"tet"</span></span>
<span><span class="op">)</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb19"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">sjPlot</span><span class="fu">::</span><span class="fu"><a href="https://strengejacke.github.io/sjPlot/reference/tab_fa.html">tab_fa</a></span><span class="op">(</span></span>
<span>  <span class="va">modelo_2f_2</span>,</span>
<span>  title <span class="op">=</span> <span class="st">"Cargas factoriales AFE 2 factores v2"</span>,</span>
<span>  sort <span class="op">=</span> <span class="cn">TRUE</span>,</span>
<span>  fctr.load.tlrn <span class="op">=</span> <span class="fl">0.2</span>,</span>
<span>  var.labels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Hablar con otra persona"</span>, </span>
<span>  <span class="st">"Comunicarse por mensajes o chat"</span>, </span>
<span>  <span class="st">"Leer libros, diarios o revistas"</span>,</span>
<span>  <span class="st">"Escuchar música"</span>,</span>
<span>  <span class="st">"Ver videos, películas o series"</span>,</span>
<span>  <span class="st">"Comunicarse por videollamada"</span>,</span>
<span>  <span class="st">"Usar Facebook"</span>,</span>
<span>  <span class="st">"Usar Instagram"</span>,</span>
<span>  <span class="st">"Usar Twitter"</span>,</span>
<span>  <span class="st">"Usar otras redes sociales"</span>,</span>
<span>  <span class="st">"Uso de Zoom, Meet o Skype"</span>,</span>
<span>  <span class="st">"Aprender algo a través de internet"</span></span>
<span>  <span class="op">)</span></span>
<span>  <span class="op">)</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Cargas factoriales AFE 2 factores v2</caption>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th" style="border-top: double black; padding: 0.2cm">&nbsp;</th>
<th data-quarto-table-cell-role="th" style="border-top: double black; padding: 0.2cm">Factor 1</th>
<th data-quarto-table-cell-role="th" style="border-top: double black; padding: 0.2cm">Factor 2</th>
</tr>
<tr class="even">
<td style="border-top: 1px solid black">Usar Facebook</td>
<td style="text-align: center; padding: 0.2cm; border-top: 1px solid black;">0.98</td>
<td style="text-align: center; padding: 0.2cm; color: #cccccc; border-top: 1px solid black;">-0.04</td>
</tr>
<tr class="odd">
<td>Usar Instagram</td>
<td style="text-align: center; padding: 0.2cm;">0.92</td>
<td style="text-align: center; padding: 0.2cm; color: #cccccc;">-0.03</td>
</tr>
<tr class="even">
<td>Usar Twitter</td>
<td style="text-align: center; padding: 0.2cm;">0.85</td>
<td style="text-align: center; padding: 0.2cm; color: #cccccc;">-0.07</td>
</tr>
<tr class="odd">
<td>Hablar con otra persona</td>
<td style="text-align: center; padding: 0.2cm;">0.78</td>
<td style="text-align: center; padding: 0.2cm; color: #cccccc;">-0.04</td>
</tr>
<tr class="even">
<td>Comunicarse por mensajes o chat</td>
<td style="text-align: center; padding: 0.2cm;">0.73</td>
<td style="text-align: center; padding: 0.2cm; color: #cccccc;">0.26</td>
</tr>
<tr class="odd">
<td>Usar otras redes sociales</td>
<td style="text-align: center; padding: 0.2cm;">0.72</td>
<td style="text-align: center; padding: 0.2cm; color: #cccccc;">0.00</td>
</tr>
<tr class="even">
<td>Comunicarse por videollamada</td>
<td style="text-align: center; padding: 0.2cm;">0.69</td>
<td style="text-align: center; padding: 0.2cm; color: #cccccc;">0.24</td>
</tr>
<tr class="odd">
<td>Ver videos, películas o series</td>
<td style="text-align: center; padding: 0.2cm; color: #cccccc;">-0.06</td>
<td style="text-align: center; padding: 0.2cm;">0.87</td>
</tr>
<tr class="even">
<td>Escuchar música</td>
<td style="text-align: center; padding: 0.2cm; color: #cccccc;">0.03</td>
<td style="text-align: center; padding: 0.2cm;">0.84</td>
</tr>
<tr class="odd">
<td>Aprender algo a través de internet</td>
<td style="text-align: center; padding: 0.2cm; color: #cccccc;">0.03</td>
<td style="text-align: center; padding: 0.2cm;">0.81</td>
</tr>
<tr class="even">
<td>Uso de Zoom, Meet o Skype</td>
<td style="text-align: center; padding: 0.2cm; color: #cccccc;">0.03</td>
<td style="text-align: center; padding: 0.2cm;">0.79</td>
</tr>
<tr class="odd">
<td>Leer libros, diarios o revistas</td>
<td style="text-align: center; padding: 0.2cm; color: #cccccc;">0.14</td>
<td style="text-align: center; padding: 0.2cm;">0.64</td>
</tr>
</tbody>
</table>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb20"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">modelo_2f_2</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Factor Analysis using method =  pa
Call: fa(r = tech_data_2, nfactors = 2, rotate = "oblimin", fm = "pa", 
    cor = "tet")
Standardized loadings (pattern matrix) based upon correlation matrix
                 PA1   PA2   h2    u2 com
TECNOLOGIA2_1   0.78 -0.04 0.56 0.441 1.0
TECNOLOGIA2_3   0.73  0.26 0.90 0.096 1.2
TECNOLOGIA2_7   0.14  0.64 0.57 0.434 1.1
TECNOLOGIA2_10  0.03  0.84 0.73 0.267 1.0
TECNOLOGIA2_11 -0.06  0.87 0.67 0.325 1.0
TECNOLOGIA2_12  0.69  0.24 0.80 0.196 1.2
TECNOLOGIA2_13  0.98 -0.04 0.90 0.097 1.0
TECNOLOGIA2_14  0.92 -0.03 0.81 0.186 1.0
TECNOLOGIA2_16  0.85 -0.07 0.64 0.365 1.0
TECNOLOGIA2_15  0.72  0.00 0.52 0.476 1.0
TECNOLOGIA7_1   0.03  0.79 0.66 0.336 1.0
TECNOLOGIA7_2   0.03  0.81 0.69 0.308 1.0

                       PA1  PA2
SS loadings           4.96 3.52
Proportion Var        0.41 0.29
Cumulative Var        0.41 0.71
Proportion Explained  0.59 0.41
Cumulative Proportion 0.59 1.00

 With factor correlations of 
     PA1  PA2
PA1 1.00 0.78
PA2 0.78 1.00

Mean item complexity =  1.1
Test of the hypothesis that 2 factors are sufficient.

df null model =  66  with the objective function =  13.66 with Chi Square =  24358.42
df of  the model are 43  and the objective function was  2.6 

The root mean square of the residuals (RMSR) is  0.05 
The df corrected root mean square of the residuals is  0.06 

The harmonic n.obs is  1760 with the empirical chi square  531.61  with prob &lt;  0.00000000000000000000000000000000000000000000000000000000000000000000000000000000000018 
The total n.obs was  1789  with Likelihood Chi Square =  4640.34  with prob &lt;  0 

Tucker Lewis Index of factoring reliability =  0.709
RMSEA index =  0.244  and the 90 % confidence intervals are  0.239 0.251
BIC =  4318.3
Fit based upon off diagonal values = 0.99
Measures of factor score adequacy             
                                                   PA1  PA2
Correlation of (regression) scores with factors   0.99 0.96
Multiple R square of scores with factors          0.98 0.93
Minimum correlation of possible factor scores     0.96 0.86</code></pre>
</div>
</div>
<p>El ajuste global del modelo fue aceptable. Las cargas factoriales presentaron una magnitud alta, entre 0.69 y 0.98 en la dimensión de Socialización y entre 0.64 y 0.87 en la dimensión de Ocio y Entretenimiento. La comunalidad de los ítems muestra una puntuación adecuada (&gt;0.5), las cargas factoriales SS indican una buen ajuste a la estructura bidimensional y la varianza total explicada por el modelo es alta, del 71% (41% correspondiente al factor de Socialización y 29% al de Ocio y Entretenimiento). Ambos factores tienen una alta correlación, de 0.78, lo cual sugiere que ambas dimensiones, aunque distinguibles, están fuertemente relacionadas en los sujetos. Esto indica que los adultos mayores que más utilizan los dispositivos digitales para socializar son a su vez los que más lo hacen para entretenerse.</p>
</section><section id="análisis-de-confiabilidad" class="level4" data-number="6.4.3"><h4 data-number="6.4.3" class="anchored" data-anchor-id="análisis-de-confiabilidad">
<span class="header-section-number">6.4.3</span> Análisis de confiabilidad</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb22"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">socializacion</span> <span class="op">&lt;-</span> <span class="va">tech_data_2</span> <span class="op">|&gt;</span> <span class="fu">select</span><span class="op">(</span><span class="va">TECNOLOGIA2_1</span>, <span class="va">TECNOLOGIA2_3</span>, <span class="va">TECNOLOGIA2_12</span>, <span class="va">TECNOLOGIA2_13</span>, <span class="va">TECNOLOGIA2_14</span>, <span class="va">TECNOLOGIA2_16</span>, <span class="va">TECNOLOGIA2_15</span><span class="op">)</span></span>
<span></span>
<span><span class="va">ocio</span> <span class="op">&lt;-</span> <span class="va">tech_data_2</span> <span class="op">|&gt;</span> <span class="fu">select</span><span class="op">(</span><span class="va">TECNOLOGIA2_7</span>, <span class="va">TECNOLOGIA2_10</span>, <span class="va">TECNOLOGIA2_11</span>, <span class="va">TECNOLOGIA7_1</span>, <span class="va">TECNOLOGIA7_2</span><span class="op">)</span></span>
<span></span>
<span><span class="va">omega_social</span> <span class="op">&lt;-</span> <span class="fu">psych</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/psych/man/omega.html">omega</a></span><span class="op">(</span><span class="va">socializacion</span>, <span class="fl">1</span>, <span class="st">"pa"</span>, poly <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span></span>
<span><span class="va">omega_ocio</span> <span class="op">&lt;-</span> <span class="fu">psych</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/psych/man/omega.html">omega</a></span><span class="op">(</span><span class="va">ocio</span>, <span class="fl">1</span>, <span class="st">"pa"</span>, poly <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span></span>
<span><span class="va">confiabilidad</span> <span class="op">&lt;-</span> <span class="fu">tibble</span><span class="op">(</span></span>
<span>  <span class="st">"Dimensión"</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Socialización"</span>, <span class="st">"Ocio y Entretenimiento"</span><span class="op">)</span>,</span>
<span>  <span class="st">"Alpha Ordinal"</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">omega_social</span><span class="op">$</span><span class="va">alpha</span>, <span class="va">omega_ocio</span><span class="op">$</span><span class="va">alpha</span><span class="op">)</span>,</span>
<span>  <span class="st">"Omega de McDonald"</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">omega_social</span><span class="op">$</span><span class="va">omega.tot</span>, <span class="va">omega_ocio</span><span class="op">$</span><span class="va">omega.tot</span><span class="op">)</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="va">tabla_conf</span> <span class="op">&lt;-</span> <span class="fu">qflextable</span><span class="op">(</span><span class="va">confiabilidad</span><span class="op">)</span> <span class="op">|&gt;</span> <span class="fu">theme_vanilla</span><span class="op">(</span><span class="op">)</span> <span class="op">|&gt;</span> <span class="fu">colformat_double</span><span class="op">(</span>digits <span class="op">=</span> <span class="fl">2</span><span class="op">)</span></span>
<span></span>
<span><span class="va">tabla_conf</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="tabwid">
<style>.cl-eefd4206{}.cl-eef92b3a{font-family:'DejaVu Sans';font-size:11pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-eef92b4e{font-family:'DejaVu Sans';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-eefae7a4{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-eefae7ae{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-eefafa00{width:2.052in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-eefafa01{width:1.324in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-eefafa0a{width:1.884in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-eefafa0b{width:2.052in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-eefafa0c{width:1.324in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-eefafa0d{width:1.884in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-eefafa14{width:2.052in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-eefafa15{width:1.324in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-eefafa16{width:1.884in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style>
<table data-quarto-disable-processing="true" class="cl-eefd4206">
<thead><tr style="overflow-wrap:break-word;">
<th class="cl-eefafa00"><p class="cl-eefae7a4"><span class="cl-eef92b3a">Dimensión</span></p></th>
<th class="cl-eefafa01"><p class="cl-eefae7ae"><span class="cl-eef92b3a">Alpha Ordinal</span></p></th>
<th class="cl-eefafa0a"><p class="cl-eefae7ae"><span class="cl-eef92b3a">Omega de McDonald</span></p></th>
</tr></thead>
<tbody>
<tr style="overflow-wrap:break-word;">
<td class="cl-eefafa0b"><p class="cl-eefae7a4"><span class="cl-eef92b4e">Socialización</span></p></td>
<td class="cl-eefafa0c"><p class="cl-eefae7ae"><span class="cl-eef92b4e">0.95</span></p></td>
<td class="cl-eefafa0d"><p class="cl-eefae7ae"><span class="cl-eef92b4e">0.95</span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-eefafa14"><p class="cl-eefae7a4"><span class="cl-eef92b4e">Ocio y Entretenimiento</span></p></td>
<td class="cl-eefafa15"><p class="cl-eefae7ae"><span class="cl-eef92b4e">0.91</span></p></td>
<td class="cl-eefafa16"><p class="cl-eefae7ae"><span class="cl-eef92b4e">0.91</span></p></td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Debido a la naturaleza dicotómica de los ítems que componen ambos factores, la consistencia interna de cada subescala se estimó través de Alfa Ordinal y coeficiente omega de McDonald, de forma independiente para cada subescala. Los resultados indicaron niveles de fiabilidad excelentes para ambas dimensiones. El factor de Socialización obtuvo un Alpha Ordinal de 0.95 y un coeficiente omega de McDonald de 0.95, mientras que el factor de Ocio y Entretenimiento presentó un Alpha ordinal de 0.91 y un coeficiente omega de McDonald de 0.91. Ambas escalas tienen una alta consistencia interna, con una buena relación entre sus mediciones y los ítems que las componen, por lo que se procederá a la creación de los índices y los análisis bivariados para comprobar las hipótesis del estudio.</p>
</section></section><section id="resultados-bivariados" class="level3" data-number="6.5"><h3 data-number="6.5" class="anchored" data-anchor-id="resultados-bivariados">
<span class="header-section-number">6.5</span> Resultados bivariados</h3>
<section id="construcción-del-índice" class="level4" data-number="6.5.1"><h4 data-number="6.5.1" class="anchored" data-anchor-id="construcción-del-índice">
<span class="header-section-number">6.5.1</span> Construcción del índice</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb23"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">items_social</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"TECNOLOGIA2_1"</span>, <span class="st">"TECNOLOGIA2_3"</span>, <span class="st">"TECNOLOGIA2_12"</span>, </span>
<span>                  <span class="st">"TECNOLOGIA2_13"</span>, <span class="st">"TECNOLOGIA2_14"</span>, <span class="st">"TECNOLOGIA2_16"</span>, </span>
<span>                  <span class="st">"TECNOLOGIA2_15"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">items_ocio</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"TECNOLOGIA2_7"</span>, <span class="st">"TECNOLOGIA2_10"</span>, <span class="st">"TECNOLOGIA2_11"</span>, </span>
<span>                <span class="st">"TECNOLOGIA7_1"</span>, <span class="st">"TECNOLOGIA7_2"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">vars_indice</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"TECNOLOGIA2_1"</span>, <span class="st">"TECNOLOGIA2_3"</span>, <span class="st">"TECNOLOGIA2_7"</span>, <span class="st">"TECNOLOGIA2_10"</span>, </span>
<span>                 <span class="st">"TECNOLOGIA2_11"</span>, <span class="st">"TECNOLOGIA2_12"</span>, <span class="st">"TECNOLOGIA2_13"</span>, </span>
<span>                 <span class="st">"TECNOLOGIA2_14"</span>, <span class="st">"TECNOLOGIA2_16"</span>, <span class="st">"TECNOLOGIA2_15"</span>, </span>
<span>                 <span class="st">"TECNOLOGIA7_1"</span>, <span class="st">"TECNOLOGIA7_2"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">datos_biv</span> <span class="op">&lt;-</span> <span class="va">datos</span> <span class="op">|&gt;</span></span>
<span>    <span class="fu">select</span><span class="op">(</span><span class="va">`AÑO`</span>, <span class="va">SEXO</span>, <span class="va">EDAD</span>, <span class="va">EDUCACION</span>, <span class="fu">starts_with</span><span class="op">(</span><span class="st">"TECNOLOGIA1"</span><span class="op">)</span>, <span class="fu">starts_with</span><span class="op">(</span><span class="st">"TECNOLOGIA2"</span><span class="op">)</span>, <span class="va">TECNOLOGIA7_1</span>, <span class="va">TECNOLOGIA7_2</span>, <span class="fu">starts_with</span><span class="op">(</span><span class="st">"LUBBEN"</span><span class="op">)</span>, <span class="fu">starts_with</span><span class="op">(</span><span class="st">"ALONE"</span><span class="op">)</span>, <span class="fu">starts_with</span><span class="op">(</span><span class="st">"DEPRESS"</span><span class="op">)</span>, <span class="op">-</span><span class="va">TECNOLOGIA2_4</span>, <span class="op">-</span><span class="va">TECNOLOGIA2_8</span>, <span class="op">-</span><span class="va">TECNOLOGIA2_9</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>    <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">`AÑO`</span> <span class="op">==</span> <span class="fl">2022</span><span class="op">)</span></span>
<span></span>
<span><span class="va">datos_biv</span> <span class="op">&lt;-</span> <span class="va">datos_biv</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu">mutate</span><span class="op">(</span>TECNOLOGIA1 <span class="op">=</span> <span class="fu">na_if</span><span class="op">(</span><span class="va">TECNOLOGIA1</span>, <span class="fl">5</span><span class="op">)</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">mutate</span><span class="op">(</span><span class="fu">across</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">TECNOLOGIA7_1</span>, <span class="va">TECNOLOGIA7_2</span><span class="op">)</span>, <span class="op">~</span> <span class="fu">na_if</span><span class="op">(</span><span class="va">.</span>, <span class="fl">3</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">mutate</span><span class="op">(</span><span class="fu">across</span><span class="op">(</span><span class="fu">all_of</span><span class="op">(</span><span class="va">vars_indice</span><span class="op">)</span>, <span class="op">~</span> <span class="fl">2</span> <span class="op">-</span> <span class="va">.</span><span class="op">)</span><span class="op">)</span>  <span class="op">|&gt;</span> <span class="co"># Se restan los puntajes a 2 para invertir el índice (en el que 1 significa si y 2 significa no) y que 0 sea el puntaje mínimo </span></span>
<span>  <span class="fu">mutate</span><span class="op">(</span>socializacion <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/colSums.html">rowSums</a></span><span class="op">(</span><span class="fu">pick</span><span class="op">(</span><span class="fu">all_of</span><span class="op">(</span><span class="va">items_social</span><span class="op">)</span><span class="op">)</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu">mutate</span><span class="op">(</span>ocio <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/colSums.html">rowSums</a></span><span class="op">(</span><span class="fu">pick</span><span class="op">(</span><span class="fu">all_of</span><span class="op">(</span><span class="va">items_ocio</span><span class="op">)</span><span class="op">)</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu">mutate</span><span class="op">(</span>SEXO <span class="op">=</span> <span class="fu">as_factor</span><span class="op">(</span><span class="va">SEXO</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="fu">var_label</span><span class="op">(</span><span class="va">datos_biv</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>socializacion <span class="op">=</span> <span class="st">"Uso de dispositivos digitales para socialización"</span>,</span>
<span>ocio <span class="op">=</span> <span class="st">"Uso de dispositivos digitales para ocio y entretenimiento"</span>,</span>
<span>   ALONE1_ <span class="op">=</span> <span class="st">"Escala de soledad UCLA"</span>,</span>
<span>   LUBBENR1_ <span class="op">=</span> <span class="st">"Escala de aislamiento de Lubben"</span>,</span>
<span>   DEPRESSIVE1_ <span class="op">=</span> <span class="st">"Escala de depresión Yesavage"</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="va">sum</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>function (..., na.rm = FALSE)  .Primitive("sum")</code></pre>
</div>
</div>
<p>Las escalas de cada dimensión fueron creados mediante la suma simple de todas las variables, utilizando pairwise como método de manejo de casos perdidos. Cabe destacar que todas las variables fueron invertidas, ya que en cada ítem un mayor resultado significaba un menor uso de tecnología (en la batería, 1 significa que si utilizaron un dispositivo digital para esa tarea y 2 que no lo hicieron), y recodificadas para que el valor mínimo fuera 0. Esto se realiza para facilitar la interpretación de los análisis posteriores. La estimación del AFE, Alpha, omega y todos los análisis anteriores también fueron conducidos sobre los ítems previamente invertidos.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb25"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">table1</span><span class="op">(</span><span class="op">~</span> <span class="va">socializacion</span> <span class="op">+</span> <span class="va">ocio</span> <span class="op">|</span> <span class="va">SEXO</span>, data <span class="op">=</span> <span class="va">datos_biv</span>, caption<span class="op">=</span><span class="st">"Descriptivos índices por sexo"</span>, footnote <span class="op">=</span> <span class="st">"Elaboración propia con datos de la ENCVV 2022"</span><span class="op">)</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="Rtable1"><table class="Rtable1">
<caption>Descriptivos índices por sexo</caption>

<thead><tr>
<th class="rowlabel firstrow lastrow"></th>
<th class="firstrow lastrow"><span class="stratlabel">Hombre<br><span class="stratn">(N=592)</span></span></th>
<th class="firstrow lastrow"><span class="stratlabel">Mujer<br><span class="stratn">(N=1197)</span></span></th>
<th class="firstrow lastrow"><span class="stratlabel">Overall<br><span class="stratn">(N=1789)</span></span></th>
</tr></thead>
<tfoot><tr><td colspan="4" class="Rtable1-footnote">
<p>Elaboración propia con datos de la ENCVV 2022</p>
</td></tr></tfoot>
<tbody>
<tr>
<td class="rowlabel firstrow">Uso de dispositivos digitales para socialización</td>
<td class="firstrow"></td>
<td class="firstrow"></td>
<td class="firstrow"></td>
</tr>
<tr>
<td class="rowlabel">Mean (SD)</td>
<td>2.40 (1.85)</td>
<td>2.85 (1.88)</td>
<td>2.70 (1.88)</td>
</tr>
<tr>
<td class="rowlabel lastrow">Median [Min, Max]</td>
<td class="lastrow">2.00 [0, 7.00]</td>
<td class="lastrow">3.00 [0, 7.00]</td>
<td class="lastrow">3.00 [0, 7.00]</td>
</tr>
<tr>
<td class="rowlabel firstrow">Uso de dispositivos digitales para ocio y entretenimiento</td>
<td class="firstrow"></td>
<td class="firstrow"></td>
<td class="firstrow"></td>
</tr>
<tr>
<td class="rowlabel">Mean (SD)</td>
<td>0.943 (1.40)</td>
<td>1.09 (1.48)</td>
<td>1.04 (1.46)</td>
</tr>
<tr>
<td class="rowlabel lastrow">Median [Min, Max]</td>
<td class="lastrow">0 [0, 5.00]</td>
<td class="lastrow">0 [0, 5.00]</td>
<td class="lastrow">0 [0, 5.00]</td>
</tr>
</tbody>
</table></div>
</div>
</div>
<p>Con respecto a los descriptivos generales de los factores, la primera escala tiene un rango de 0 a 7 y la segunda de 0 a 5, en concordancia con la cantidad de variables presente en cada una. En el caso de la dimensión de socialización, la media es de 2.7 (D.E. = 1.88), y en el del índice de ocio de 1.04 (D.E. = 1.46). En ambas escalas, las mujeres muestran un mejor rendimiento, aventajando a sus pares masculinos en 0.15 puntos en la dimensión de Socialización, y en 0.45 puntos en la dimensión de Ocio y Entretenimiento.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb26"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">model_alone</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">ALONE1_</span> <span class="op">~</span> <span class="va">socializacion</span> <span class="op">+</span> <span class="va">ocio</span> <span class="op">+</span> <span class="va">SEXO</span> <span class="op">+</span> <span class="va">EDUCACION</span> <span class="op">+</span> <span class="va">EDAD</span>, data <span class="op">=</span> <span class="va">datos_biv</span><span class="op">)</span></span>
<span></span>
<span><span class="va">model_lubben</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">LUBBENR1_</span> <span class="op">~</span> <span class="va">socializacion</span> <span class="op">+</span> <span class="va">ocio</span> <span class="op">+</span> <span class="va">SEXO</span> <span class="op">+</span> <span class="va">EDUCACION</span> <span class="op">+</span> <span class="va">EDAD</span>, data <span class="op">=</span> <span class="va">datos_biv</span><span class="op">)</span></span>
<span></span>
<span><span class="va">model_depresion</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">DEPRESSIVE1_</span> <span class="op">~</span> <span class="va">socializacion</span> <span class="op">+</span> <span class="va">ocio</span> <span class="op">+</span> <span class="va">SEXO</span> <span class="op">+</span> <span class="va">EDUCACION</span> <span class="op">+</span> <span class="va">EDAD</span>, data <span class="op">=</span> <span class="va">datos_biv</span><span class="op">)</span></span>
<span></span>
<span><span class="fu">sjPlot</span><span class="fu">::</span><span class="fu"><a href="https://strengejacke.github.io/sjPlot/reference/tab_model.html">tab_model</a></span><span class="op">(</span><span class="va">model_alone</span>, <span class="va">model_lubben</span>, <span class="va">model_depresion</span>, title <span class="op">=</span> <span class="st">"Regresiones lineales factores y escalas de bienestar en adultos mayores"</span><span class="op">)</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Regresiones lineales factores y escalas de bienestar en adultos mayores</caption>
<colgroup>
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
</colgroup>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: normal; font-weight: bold; padding: 0.2cm;">&nbsp;</th>
<th colspan="3" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: normal; font-weight: bold; padding: 0.2cm;">Escala de soledad UCLA</th>
<th colspan="3" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: normal; font-weight: bold; padding: 0.2cm;">Escala de aislamiento de<br>
Lubben</th>
<th colspan="3" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: normal; font-weight: bold; padding: 0.2cm;">Escala de depresión<br>
Yesavage</th>
</tr>
<tr class="even">
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">Predictors</td>
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">Estimates</td>
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">CI</td>
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">p</td>
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">Estimates</td>
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">CI</td>
<td style="text-align: center;">p</td>
<td style="text-align: center;">Estimates</td>
<td style="text-align: center;">CI</td>
<td style="text-align: center;">p</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">(Intercept)</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">1.90</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">1.00&nbsp;–&nbsp;2.79</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>&lt;0.001</strong></td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">6.80</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">3.80&nbsp;–&nbsp;9.81</td>
<td style="text-align: center;"><strong>&lt;0.001</strong></td>
<td style="text-align: center;">1.24</td>
<td style="text-align: center;">0.55&nbsp;–&nbsp;1.93</td>
<td style="text-align: center;"><strong>&lt;0.001</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Uso de dispositivos<br>
digitales para<br>
socialización</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">-0.03</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">-0.09&nbsp;–&nbsp;0.03</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.307</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.52</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.32&nbsp;–&nbsp;0.72</td>
<td style="text-align: center;"><strong>&lt;0.001</strong></td>
<td style="text-align: center;">-0.11</td>
<td style="text-align: center;">-0.16&nbsp;–&nbsp;-0.07</td>
<td style="text-align: center;"><strong>&lt;0.001</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Uso de dispositivos<br>
digitales para ocio y<br>
entretenimiento</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">-0.06</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">-0.13&nbsp;–&nbsp;0.01</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.097</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.39</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.16&nbsp;–&nbsp;0.62</td>
<td style="text-align: center;"><strong>0.001</strong></td>
<td style="text-align: center;">0.03</td>
<td style="text-align: center;">-0.03&nbsp;–&nbsp;0.08</td>
<td style="text-align: center;">0.302</td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Sexo: Mujer</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.25</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.08&nbsp;–&nbsp;0.42</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>0.004</strong></td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">-0.96</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">-1.52&nbsp;–&nbsp;-0.39</td>
<td style="text-align: center;"><strong>0.001</strong></td>
<td style="text-align: center;">0.17</td>
<td style="text-align: center;">0.04&nbsp;–&nbsp;0.30</td>
<td style="text-align: center;"><strong>0.009</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">¿Cuál es su nivel de<br>
estudios?</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">-0.18</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">-0.27&nbsp;–&nbsp;-0.10</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>&lt;0.001</strong></td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.75</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.46&nbsp;–&nbsp;1.04</td>
<td style="text-align: center;"><strong>&lt;0.001</strong></td>
<td style="text-align: center;">-0.21</td>
<td style="text-align: center;">-0.27&nbsp;–&nbsp;-0.14</td>
<td style="text-align: center;"><strong>&lt;0.001</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">¿Cuál es su edad (en<br>
años)?</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">-0.00</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">-0.01&nbsp;–&nbsp;0.01</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.885</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.03</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">-0.01&nbsp;–&nbsp;0.07</td>
<td style="text-align: center;">0.122</td>
<td style="text-align: center;">0.01</td>
<td style="text-align: center;">0.00&nbsp;–&nbsp;0.02</td>
<td style="text-align: center;"><strong>0.003</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm; border-top: 1px solid;">Observations</td>
<td colspan="3" style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm; border-top: 1px solid;">1782</td>
<td colspan="3" style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm; border-top: 1px solid;">1776</td>
<td colspan="3" style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm; border-top: 1px solid;">1788</td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm;">R<sup>2</sup> / R<sup>2</sup> adjusted</td>
<td colspan="3" style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm;">0.029 / 0.026</td>
<td colspan="3" style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm;">0.092 / 0.090</td>
<td colspan="3" style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm;">0.082 / 0.079</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Para estimar los análisis bivariados y comprobar las hipótesis planteadas, se estimaron una serie de modelos de regresión lineal a través de Mínimos Cuadrados Ordinarios. En todos los modelos, se agregaron ambas escalas simultáneamente, sumando el sexo, la edad y el nivel educativo de los encuestados como variables de control.</p>
<p>El primer modelo, que tiene como variable dependiente la escala UCLA de soledad autopercibida (rango de 0 a 6), no mostró efectos significativos para ninguna de las dimensiones. El nivel de estudios si presenta un efecto significativo (p&lt;0.001) y negativo en la soledad: El aumento de un nivel educacional significa una reducción de 0.18 en la escala de soledad. El sexo también mostró un impacto en la soledad (p&lt;0.01), siendo el efecto de ser mujer un aumento de 0.25 en la escala de soledad. Este modelo es el que explica una menor porción de la varianza entre los tres, con un 2.9% de variabilidad explicada.</p>
<p>El segundo modelo, con la escala de redes sociales de Lubben como variable dependiente (rango de 0 a 30), presenta efectos significativos para ambos factores (p&lt;=0.001). Sobre la dimensión de socialización, el aumento en un punto en la escala (lo cual significa utilizar los dispositivos para una más de estas tareas) representa un aumento de 0.54 en las redes sociales de los adultos mayores. El impacto del uso de dispositivos digitales para el ocio es algo menor, teniendo un efecto de 0.39 el utilizar dispositivos digitales para el entretenimiento. El R² indica que el modelo está explicando un 9.2% de la varianza de la variable dependiente.</p>
<p>Con respecto al tercer modelo, entre los factores construidos solo la dimensión de socialización tiene un efecto significativo en los síntomas depresivos (p&lt;0.001). El efecto de utilizar dispositivos digitales para socializar es negativo, reduciendo en 0.11 el puntaje en la escala de depresión de Yesavage (que tiene un rango de 0 a 5) el utilizar los dispositivos digitales para una actividad de socialización adicional. El R² señala que el modelo está explicando un 8.2% de la varianza de la escala de depresión.</p>
<p>En síntesis, el uso de tecnologías digitales para el ocio y la socialización tiene un efecto positivo en diversos indicadores del bienestar en la vejez, controlando por el sexo, la edad y el nivel educacional. Al observar los resultados de los modelos, la socialización demuestra ser más relevante para explicar un menor riesgo de depresión y aislamiento social, mientras que no se encontraron resultados significativos para ninguna de las dimensiones en la soledad.</p>
<p>Estos resultados, en concordancia con la literatura revisada, indican que el uso de dispositivos digitales puede servir como herramienta para la población envejecida para comunicarse, entretenerse y conservar sus redes sociales. Cómo se analizó en los modelos de regresión, un mayor uso de dispositivos digitales, en especial en la dimensión de socialización, disminuye en un puntaje considerable los riesgos de síntomas depresivos y aislamiento de los adultos mayores. En el marco de una importante <em>grey digital divide</em>, parece más importante que nunca incentivar un uso positivo de las tecnologías en este grupo para que aprovechen los posibles beneficios que pueden traerles. Para esto, es crucial la elaboración de políticas de capacitación, alfabetización y creación de incentivos, ya que la adaptación es definitivamente un proceso gradual y con múltiples obstáculos, pero que, como sugieren estos resultados, puede traer grandes beneficios personales.</p>
</section></section></section><section id="referencias" class="level2" data-number="7"><h2 data-number="7" class="anchored" data-anchor-id="referencias">
<span class="header-section-number">7</span> <strong>Referencias</strong>
</h2>
<p>Barreda, M., Cantarero-Prieto, D., &amp; Pascual, M. (2024). Age, Technology, and the Digital Divide: Are They Directly Related to Mental Health Problems?&nbsp; Healthcare, 12(23), 2454. <a href="https://doi.org/10.3390/healthcare12232454" class="uri">https://doi.org/10.3390/healthcare12232454</a></p>
<p>Castells, M. (1997). La era de la información. Economía, sociedad y cultura, 1. Alianza.</p>
<p>Centro de Estudios de Vejez y Envejecimiento UC, &amp; Caja Los Andes. (2022). Sexta Encuesta Nacional de Calidad de Vida en la Vejez.<a href="https://encuestacalidaddevidaenlavejez.uc.cl">https://encuestacalidaddevidaenlavejez.uc.cl</a></p>
<p>English Longitudinal Study of Ageing. (s.f.). The data we collect. Extraído el 8 de octubre de 2025 de<a href="https://www.elsa-project.ac.uk/the-data-we-collect">https://www.elsa-project.ac.uk/the-data-we-collect</a></p>
<p>Forsman, A. K., &amp; Nordmyr, J. (2017). Psychosocial links between Internet use and mental health in later life: A systematic review of quantitative and qualitative evidence. Journal of Applied Gerontology, 36(12), 1471–1518. doi:10.1177/0733464815595509&nbsp;</p>
<p>Hoyl, M., Alessi, C., Harker, J., Josephson, K., Pietruszka, F., Koelfgen, M., &amp; al., et. (1999). Development and testing of a five-item version of the Geriatric Depression Scale. Journal of the American Geriatrics Society, 47(7), 873–878.&nbsp;</p>
<p>Hughes, M. E., Waite, L. J., Hawkley, L. C., &amp; Cacioppo, J. T. (2004). A short scale for measuring loneliness in large surveys: Results from two population-based studies. Research on Aging, 26(6), 655–672.&nbsp;</p>
<p>Ihm, J., y Hsieh, Y. P. (2015). The implications of information and communication technology use for the social well-being of older adults. Information, Communication &amp; Society, 18(10), 1123–1138. doi:10.1080/1369118x.2015.1019912</p>
<p>Institute for Social Research. (2024). Health and Retirement Study: Internet Use Questionnaire, Wave 2024 [Cuestionario]. University of Michigan.<a href="https://hrs.isr.umich.edu/documentation/questionnaires"></a><a href="https://hrs.isr.umich.edu/sites/default/files/meta/2024/core/qnaire/27hr24EOI.pdf" class="uri">https://hrs.isr.umich.edu/sites/default/files/meta/2024/core/qnaire/27hr24EOI.pdf</a></p>
<p>Instituto Nacional de Estadística. (2025). Resultados Censo 2024. <a href="https://censo2024.ine.gob.cl/resultados/" class="uri">https://censo2024.ine.gob.cl/resultados/</a>&nbsp;</p>
<p>Jun, H. J., y Kim, M. Y. (2017). What accounts for the relationship between Internet use and suicidal ideation of Korean older adults? A mediation analysis. The Journals of Gerontology, Series B: Psychological Sciences and Social Sciences, 72(5), 846– 855. doi:10.1093/geronb/gbw163&nbsp;</p>
<p>Kaye, L. (2021). Exploring the “socialness” of social media. Computers in Human Behavior Reports,3. Elsevier Ltd.&nbsp;<a href="https://doi.org/10.1016/j.chbr.2021.100083" class="uri">https://doi.org/10.1016/j.chbr.2021.100083</a>&nbsp;</p>
<p>Ley Nº 19.828 de 2002. Crea el servicio nacional del adulto mayor. 16 de septiembre del 2002. D.O. No 37.369.</p>
<p>Lifshitz, R., Nimrod, G., y Bachner, Y. G. (2018). Internet use and well-being in later life: A functional approach. Aging and Mental Health, 22(1), 85–91. <a href="https://doi.org/10.1080/13607863.2016.1232370" class="uri">https://doi.org/10.1080/13607863.2016.1232370</a>&nbsp;</p>
<p>Lubben, J., &amp; Gironda, M. (2003). Centrality of social ties to the health and well-being of older adults. Social Work and Health Care in an Aging Society, 319–350.</p>
<p>Mubarak, F., &amp; Suomi, R. (2022). Elderly Forgotten? Digital Exclusion in the Information Age and the Rising Grey Digital Divide. INQUIRY: The Journal of Health Care Organization, Provision, and Financing, 59. <a href="https://doi.org/10.1177/00469580221096272" class="uri">https://doi.org/10.1177/00469580221096272</a></p>
<p>Organización Mundial de la Salud (1 de octubre de 2025). Envejecimiento y Salud. Organización Mundial de la Salud. <a href="https://www.who.int/es/news-room/fact-sheets/detail/ageing-and-health" class="uri">https://www.who.int/es/news-room/fact-sheets/detail/ageing-and-health</a>&nbsp;</p>
<p>OECD. (2023). Survey of Adult Skills (PIAAC) 2023: Master Questionnaire [Cuestionario]. OECD Publishing. <a href="https://www.oecd.org/en/data/datasets/piaac-2nd-cycle-database.html" class="uri">https://www.oecd.org/en/data/datasets/piaac-2nd-cycle-database.html</a></p>
<p>Rosell, J., Vergés, A. (2021). The Impact of Ageism on the E-Leisure of Older People in Chile. En: Gao, Q., Zhou, J. (eds) Human Aspects of IT for the Aged Population. Technology Design and Acceptance. HCII 2021. Lecture Notes in Computer Science, 12786. Springer, Cham. <a href="https://doi.org/10.1007/978-3-030-78108-8_17" class="uri">https://doi.org/10.1007/978-3-030-78108-8_17</a>&nbsp;</p>
<p>Rosell, J., Sepúlveda, S. y Bustamante, F. (2024). Educational Gerontechnology: Toward a Comprehensive Model for the Education of Digital Technologies for Older Adults. En: Gao, Q., Zhou, J. (eds) Human Aspects of IT for the Aged Population. HCII 2024. Lecture Notes in Computer Science, (1)14725 <a href="https://link.springer.com/chapter/10.1007/978-3-031-61543-6_20" class="uri">https://link.springer.com/chapter/10.1007/978-3-031-61543-6_20</a></p>
<p>Subsecretaría de Telecomunicaciones y CADEM. (2024). Estudio Undécima Encuesta sobre acceso, usos y usuarios de Internet en Chile [PDF]. SUBTEL.<a href="https://www.subtel.gob.cl/wp-content/uploads/2025/02/Informe-Final-Subtel-Acceso-y-Uso-Internet-2024.pdf?utm_source=chatgpt.com">https://www.subtel.gob.cl/wp-content/uploads/2025/02/Informe-Final-Subtel-Acceso-y-Uso-Internet-2024.pdf</a></p>
<p>Sims, T., Reed, A. E., &amp; Carr, D. C. (2017). Information and Communication Technology Use Is Related to Higher Well-Being Among the Oldest-Old. The Journals of Gerontology. Series B, Psychological Sciences and Social Sciences, 72(5), 761-770.<a href="https://doi.org/10.1093/geronb/gbw130">https://doi.org/10.1093/geronb/gbw130</a></p>
<p>Stafford, T.F., Stafford, M.R. and Schkade, L.L. (2004). Determining Uses and Gratifications for the Internet. Decision Sciences, 35: 259-288. <a href="https://doi.org/10.1111/j.00117315.2004.02524.x" class="uri">https://doi.org/10.1111/j.00117315.2004.02524.x</a>&nbsp;</p>
<p>Szabo, A., Allen, J., Stephens, C., &amp; Alpass, F. (2019). Longitudinal Analysis of the Relationship Between Purposes of Internet Use and Well-being Among Older Adults. The Gerontologist, 59(1), 58–68. <a href="https://doi.org/10.1093/geront/gny036" class="uri">https://doi.org/10.1093/geront/gny036</a>&nbsp;</p>
<p>Wang, Y., Zhang, H., Feng, T., &amp; Wang, H. (2019). Does Internet use affect levels of depression among older adults in China? A propensity score matching approach. BMC Public Health, 19(1), 1474. doi:10.1186/s12889-019-7832-8&nbsp;</p>
<p>Van Dijk, J. (2020). The Digital Divide. Cambridge, UK: Polity Press.</p>
<p>Van Dijk, J. (2020). The Network Society. 1-384.</p>
</section></main><!-- /main column --><script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiado");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiado");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->



<script src="análisis_files/libs/quarto-html/zenscroll-min.js"></script>
</body></html>